// src/main/webapp/app/patient/patient-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { PatientDTO } from 'app/patient/patient-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function PatientList() {
  const { t } = useTranslation();
  useDocumentTitle(t('patient.list.headline'));

  const [patients, setPatients] = useState<PatientDTO[]>([]);
  const navigate = useNavigate();

  const getAllPatients = async () => {
    try {
      const response = await axios.get('/api/patients');
      setPatients(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/patients/' + id);
      navigate('/patients', {
            state: {
              msgInfo: t('patient.delete.success')
            }
          });
      getAllPatients();
    } catch (error: any) {
      if (error?.response?.data?.code === 'REFERENCED') {
        const messageParts = error.response.data.message.split(',');
        navigate('/patients', {
              state: {
                msgError: t(messageParts[0]!, { id: messageParts[1]! })
              }
            });
        return;
      }
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllPatients();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('patient.list.headline')}</h1>
      <div>
        <Link to="/patients/add" className="btn btn-primary ms-2">{t('patient.list.createNew')}</Link>
      </div>
    </div>
    {!patients || patients.length === 0 ? (
    <div>{t('patient.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('patient.id.label')}</th>
            <th scope="col">{t('patient.fullname.label')}</th>
            <th scope="col">{t('patient.cpf.label')}</th>
            <th scope="col">{t('patient.rg.label')}</th>
            <th scope="col">{t('patient.socialname.label')}</th>
            <th scope="col">{t('patient.user.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {patients.map((patient) => (
          <tr key={patient.id}>
            <td>{patient.id}</td>
            <td>{patient.fullname}</td>
            <td>{patient.cpf}</td>
            <td>{patient.rg}</td>
            <td>{patient.socialname}</td>
            <td>{patient.user}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/patients/edit/' + patient.id} className="btn btn-sm btn-secondary">{t('patient.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(patient.id!)} className="btn btn-sm btn-secondary">{t('patient.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}

// src/main/webapp/app/patient/patient-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { PatientService } from 'app/patient/patient.service';
import { PatientDTO } from 'app/patient/patient.model';


@Component({
  selector: 'app-patient-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './patient-list.component.html'})
export class PatientListComponent implements OnInit, OnDestroy {

  patientService = inject(PatientService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  patients?: PatientDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@patient.delete.success:Patient was removed successfully.`,
      'patient.responsible.patient.referenced': $localize`:@@patient.responsible.patient.referenced:This entity is still referenced by Responsible ${details?.id} via field Patient.`,
      'patient.schedule.patient.referenced': $localize`:@@patient.schedule.patient.referenced:This entity is still referenced by Schedule ${details?.id} via field Patient.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.patientService.getAllPatients()
        .subscribe({
          next: (data) => this.patients = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.patientService.deletePatient(id)
        .subscribe({
          next: () => this.router.navigate(['/patients'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => {
            if (error.error?.code === 'REFERENCED') {
              const messageParts = error.error.message.split(',');
              this.router.navigate(['/patients'], {
                state: {
                  msgError: this.getMessage(messageParts[0], { id: messageParts[1] })
                }
              });
              return;
            }
            this.errorHandler.handleServerError(error.error)
          }
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@patient.list.headline">Patients</h1>
    <div>
        <a routerLink="/patients/add" class="btn btn-primary ms-2" i18n="@@patient.list.createNew">Create new Patient</a>
    </div>
</div>
@if (!patients || patients.length === 0) {
<div i18n="@@patient.list.empty">No Patients could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@patient.id.label">Id</th>
                <th scope="col" i18n="@@patient.fullname.label">Fullname</th>
                <th scope="col" i18n="@@patient.cpf.label">Cpf</th>
                <th scope="col" i18n="@@patient.rg.label">Rg</th>
                <th scope="col" i18n="@@patient.socialname.label">Socialname</th>
                <th scope="col" i18n="@@patient.user.label">User</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (patient of patients; track patient.id) {
            <tr>
                <td>{{ patient.id }}</td>
                <td>{{ patient.fullname }}</td>
                <td>{{ patient.cpf }}</td>
                <td>{{ patient.rg }}</td>
                <td>{{ patient.socialname }}</td>
                <td>{{ patient.user }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/patients/edit', patient.id]" class="btn btn-sm btn-secondary" i18n="@@patient.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(patient.id!)" class="btn btn-sm btn-secondary" i18n="@@patient.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}
