// src/main/webapp/app/patient/patient-add.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { PatientDTO } from 'app/patient/patient-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    fullname: yup.string().emptyToNull().max(255).required(),
    cpf: yup.string().emptyToNull().max(255),
    rg: yup.string().emptyToNull().max(255),
    socialname: yup.string().emptyToNull().max(255),
    user: yup.number().integer().emptyToNull().required(),
    documents: yup.array(yup.number().required()).emptyToNull().json(),
    healthInsurances: yup.array(yup.number().required()).emptyToNull().json()
  });
}

export default function PatientAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('patient.add.headline'));

  const navigate = useNavigate();
  const [userValues, setUserValues] = useState<Map<number,string>>(new Map());
  const [documentsValues, setDocumentsValues] = useState<Map<number,string>>(new Map());
  const [healthInsurancesValues, setHealthInsurancesValues] = useState<Map<number,string>>(new Map());

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const getMessage = (key: string) => {
    const messages: Record<string, string> = {
      PATIENT_CPF_UNIQUE: t('exists.patient.cpf'),
      PATIENT_USER_UNIQUE: t('Exists.patient.user')
    };
    return messages[key];
  };

  const prepareRelations = async () => {
    try {
      const userValuesResponse = await axios.get('/api/patients/userValues');
      setUserValues(userValuesResponse.data);
      const documentsValuesResponse = await axios.get('/api/patients/documentsValues');
      setDocumentsValues(documentsValuesResponse.data);
      const healthInsurancesValuesResponse = await axios.get('/api/patients/healthInsurancesValues');
      setHealthInsurancesValues(healthInsurancesValuesResponse.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareRelations();
  }, []);

  const createPatient = async (data: PatientDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/patients', data);
      navigate('/patients', {
            state: {
              msgSuccess: t('patient.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t, getMessage);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('patient.add.headline')}</h1>
      <div>
        <Link to="/patients" className="btn btn-secondary">{t('patient.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createPatient)} noValidate>
      <InputRow useFormResult={useFormResult} object="patient" field="fullname" required={true} />
      <InputRow useFormResult={useFormResult} object="patient" field="cpf" />
      <InputRow useFormResult={useFormResult} object="patient" field="rg" />
      <InputRow useFormResult={useFormResult} object="patient" field="socialname" />
      <InputRow useFormResult={useFormResult} object="patient" field="user" required={true} type="select" options={userValues} />
      <InputRow useFormResult={useFormResult} object="patient" field="documents" type="multiselect" options={documentsValues} />
      <InputRow useFormResult={useFormResult} object="patient" field="healthInsurances" type="multiselect" options={healthInsurancesValues} />
      <input type="submit" value={t('patient.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/patient/patient-add.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { PatientService } from 'app/patient/patient.service';
import { PatientDTO } from 'app/patient/patient.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';


@Component({
  selector: 'app-patient-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './patient-add.component.html'
})
export class PatientAddComponent implements OnInit {

  patientService = inject(PatientService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  userValues?: Map<number,string>;
  documentsValues?: Map<number,string>;
  healthInsurancesValues?: Map<number,string>;

  addForm = new FormGroup({
    fullname: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    cpf: new FormControl(null, [Validators.maxLength(255)]),
    rg: new FormControl(null, [Validators.maxLength(255)]),
    socialname: new FormControl(null, [Validators.maxLength(255)]),
    user: new FormControl(null, [Validators.required]),
    documents: new FormControl([]),
    healthInsurances: new FormControl([])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@patient.create.success:Patient was created successfully.`,
      PATIENT_CPF_UNIQUE: $localize`:@@Exists.patient.cpf:This Cpf is already taken.`,
      PATIENT_USER_UNIQUE: $localize`:@@Exists.patient.user:This User is already referenced by another Patient.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.patientService.getUserValues()
        .subscribe({
          next: (data) => this.userValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.patientService.getDocumentsValues()
        .subscribe({
          next: (data) => this.documentsValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.patientService.getHealthInsurancesValues()
        .subscribe({
          next: (data) => this.healthInsurancesValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new PatientDTO(this.addForm.value);
    this.patientService.createPatient(data)
        .subscribe({
          next: () => this.router.navigate(['/patients'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@patient.add.headline">Add Patient</h1>
    <div>
        <a routerLink="/patients" class="btn btn-secondary" i18n="@@patient.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="fullname" i18n-label="@@patient.fullname.label" label="Fullname" />
    <app-input-row [group]="addForm" field="cpf" i18n-label="@@patient.cpf.label" label="Cpf" />
    <app-input-row [group]="addForm" field="rg" i18n-label="@@patient.rg.label" label="Rg" />
    <app-input-row [group]="addForm" field="socialname" i18n-label="@@patient.socialname.label" label="Socialname" />
    <app-input-row [group]="addForm" field="user" rowType="select" [options]="userValues" i18n-label="@@patient.user.label" label="User" />
    <app-input-row [group]="addForm" field="documents" rowType="multiselect" [options]="documentsValues" i18n-label="@@patient.documents.label" label="Documents" />
    <app-input-row [group]="addForm" field="healthInsurances" rowType="multiselect" [options]="healthInsurancesValues" i18n-label="@@patient.healthInsurances.label" label="Health Insurances" />
    <input type="submit" i18n-value="@@patient.add.headline" value="Add Patient" class="btn btn-primary mt-4" />
</form>
