// src/main/webapp/app/common/input-row/input-row.tsx
import React, { useEffect, useRef, ChangeEvent, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { UseFormReturn } from 'react-hook-form';
import { useNavigate } from 'react-router';
import { upload, FileData } from 'app/common/file-upload';
import { handleServerError } from 'app/common/utils';
import InputErrors from 'app/common/input-row/input-errors';
import flatpickr from 'flatpickr';


export default function InputRow({ useFormResult, object, field, type = 'text',
    required = false, disabled = false, inputClass = '', options, downloadLink }: InputRowParams) {
  const { t } = useTranslation();
  const label = t(object + '.' + field + '.label') + (required ? '*' : '');

  const { register, setValue, formState: { errors }, watch } = useFormResult;
  let optionsMap = new Map();
  if (options && options instanceof Map) {
    optionsMap = options;
  } else if (options) {
    optionsMap = new Map(Object.entries(options));
  }
  const navigate = useNavigate();
  const currentValue = watch(field);
  const [currentFile, setCurrentFile] = useState<FileData|null>(null);
  const [withDownloads, setWithDownloads] = useState(true);

  const getInputClasses = () => {
    return (errors[field] ? 'is-invalid ' : '') + inputClass;
  };

  const fileDelete = () => {
    setValue(field, null);
    setWithDownloads(false);
  };

  const fileChanged = async (event: ChangeEvent<HTMLInputElement>) => {
    const $filesInput = event.target as HTMLInputElement;
    setValue(field, null);
    if (!$filesInput.files) {
      return;
    }
    try {
      const uploadedFile = await upload($filesInput.files[0]!);
      setValue(field, JSON.stringify(uploadedFile));
      $filesInput.value = '';
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  if (type === 'file') {
    useEffect(() => {
      setCurrentFile(JSON.parse(currentValue || null));
    }, [currentValue]);
  }

  if (type === 'radio' && !required) {
    useEffect(() => {
      setValue(field, '');
    }, []);
  }

  const rowRef = useRef<HTMLDivElement|null>(null);
  let datepicker: string|undefined;
  if (type === 'datepicker' || type === 'timepicker' || type === 'datetimepicker') {
    datepicker = type;
    type = 'text';

    useEffect(() => {
      const flatpickrConfig:any = {
        allowInput: true,
        time_24hr: true,
        enableSeconds: true
      };
      if (datepicker === 'datepicker') {
        flatpickrConfig.dateFormat = 'Y-m-d';
      } else if (datepicker === 'timepicker') {
        flatpickrConfig.enableTime = true;
        flatpickrConfig.noCalendar = true;
        flatpickrConfig.dateFormat = 'H:i:S';
      } else { // datetimepicker
        flatpickrConfig.enableTime = true;
        flatpickrConfig.dateFormat = 'Y-m-dTH:i:S';
      }
      flatpickrConfig.onChange = function(_selectedDates: any, dateStr: string, _instance: any) {
        useFormResult.setValue(field, dateStr);
      };
      const input = rowRef.current!.querySelector('input') as HTMLInputElement;
      const calendar = flatpickr(input, flatpickrConfig);
      return () => calendar.destroy();
    }, []);
  }

  return (
    <div className="row mb-3" ref={rowRef}>
      {type === 'checkbox' ? (
        <div className="col-md-10 offset-md-2">
          <div className="form-check">
            <input id={field} {...register(field)} type="checkbox" disabled={disabled}
                className={'form-check-input ' + getInputClasses()} />
            <label htmlFor={field} className="form-check-label">
              {label}
            </label>
          </div>
          <InputErrors errors={errors} field={field} />
        </div>
      ) : (<>
      <label htmlFor={field} className="col-md-2 col-form-label">
        {label}
      </label>
      <div className="col-md-10">
        {type === 'text' || type === 'password' || type === 'email' || type === 'tel' || type === 'number' ? (
        <input id={field} {...register(field)} type={type} disabled={disabled}
            className={'form-control ' + getInputClasses()} />
        ) : type === 'textarea' ? (
        <textarea id={field} {...register(field)} disabled={disabled}
            className={'form-control ' + getInputClasses()}></textarea>
        ) : type === 'select' || type === 'multiselect' ? (
        <select id={field} {...register(field)} multiple={type === 'multiselect'} disabled={disabled}
            className={'form-select ' + getInputClasses()}>
          {type === 'select' && <option value="">{t('select.empty.label')}</option>}
          {Array.from(optionsMap).map(([key, value]) => (
          <option value={key} key={key}>{value}</option>
          ))}
        </select>
        ) : type === 'radio' ? (<>
        {!required &&
          <div className="form-check form-check-inline pt-2">
            <input id={field} {...register(field)} value="" type="radio" disabled={disabled}
                className={'form-check-input ' + getInputClasses()} />
            <label htmlFor={field} className="form-check-label">{t('select.empty.label')}</label>
          </div>
        }
        {Array.from(optionsMap).map(([key, value]) => (
        <div key={key} className="form-check form-check-inline pt-2">
          <input id={field + '_' + key} {...register(field)} value={key} type="radio" disabled={disabled}
              className={'form-check-input ' + getInputClasses()} />
          <label htmlFor={field + '_' + key} className="form-check-label">{value}</label>
        </div>
        ))}
        </>) : type === 'file' ? (<>
        <input id={field} {...register(field)} type="hidden" disabled={disabled} />
        <input id={field + '_file'} type="file" disabled={disabled} onChange={fileChanged}
            className={'form-control ' + (currentFile === null ? '' : 'd-none ') + getInputClasses()} />
        {currentFile !== null &&
          <div className="form-control-plaintext d-flex align-items-baseline gap-2">
            <span>{currentFile.fileName}</span>
            {withDownloads && downloadLink &&
              <a href={process.env.API_PATH + downloadLink + '/' + currentFile!.fileName} target="_blank" className="small text-secondary">{t('file.open')}</a>
            }
            <span role="button" onClick={fileDelete} className="small text-secondary text-decoration-underline">{t('file.delete')}</span>
          </div>
        }
        </>) : (<></>)}
        <InputErrors errors={errors} field={field} />
      </div>
      </>)}
    </div>
  );
}

interface InputRowParams {

  useFormResult: UseFormReturn<any, any, any|undefined>;
  object: string;
  field: string;
  type?: string;
  required?: boolean;
  disabled?: boolean;
  inputClass?: string;
  options?: Record<string, string>|Map<number, string>;
  downloadLink?: string;

}

// src/main/webapp/app/common/input-row/input-row.component.ts
import { KeyValuePipe } from '@angular/common';
import { AfterViewInit, Component, ElementRef, HostListener, inject, Input, OnChanges, OnInit } from '@angular/core';
import { AbstractControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { InputErrorsComponent } from 'app/common/input-row/input-errors.component';
import { environment } from 'environments/environment';
import { FileUploadService, FileData } from 'app/common/file-upload.injectable';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import flatpickr from 'flatpickr';


@Component({
  selector: 'app-input-row',
  templateUrl: './input-row.component.html',
  imports: [ReactiveFormsModule, InputErrorsComponent, KeyValuePipe]
})
export class InputRowComponent implements AfterViewInit, OnChanges, OnInit {

  fileUploadService = inject(FileUploadService);
  errorHandler = inject(ErrorHandler);

  @Input({ required: true })
  group?: FormGroup;

  @Input({ required: true })
  field = '';

  @Input()
  rowType = 'text';

  @Input()
  inputClass = '';

  @Input()
  options?: Record<string, string>|Map<number, string>;

  @Input({ required: true })
  label = '';

  @Input()
  downloadLink = '';

  datepicker?: 'datepicker'|'timepicker'|'datetimepicker';

  control?: AbstractControl;
  optionsMap?: Map<string|number,string>;

  currentFile: FileData|null = null;
  withDownloads = true;

  elRef = inject(ElementRef);

  ngOnInit() {
    this.control = this.group!.get(this.field)!;
    if (this.rowType === 'file') {
        this.currentFile = JSON.parse(this.control.value || null);
    }
    if (this.rowType === 'datepicker' || this.rowType === 'timepicker' || this.rowType === 'datetimepicker') {
      this.datepicker = this.rowType;
      this.rowType = 'text';
    }
  }

  ngOnChanges() {
    if (!this.options || this.options instanceof Map) {
      this.optionsMap = this.options;
    } else {
      this.optionsMap = new Map(Object.entries(this.options));
    }
  }

  ngAfterViewInit() {
    this.initDatepicker();
    if (this.rowType === 'file') {
      this.control!.valueChanges.subscribe(val => {
        this.currentFile = JSON.parse(this.control!.value || null);
      });
    }
  }

  @HostListener('input', ['$event.target'])
  onEvent(target: HTMLInputElement) {
    if (target.value === '') {
      this.control!.setValue(null);
    }
  }

  fileDownloadLink() {
    return environment.apiPath + this.downloadLink + '/' + this.currentFile!.fileName;
  }

  fileDelete() {
    this.currentFile = null;
    this.control!.setValue(null);
    this.withDownloads = false;
  }

  fileChanged(event: Event) {
    const $filesInput = event.target as HTMLInputElement;
    this.currentFile = null;
    this.control!.setValue(null);
    if (!$filesInput.files) {
      return;
    }
    this.fileUploadService.upload($filesInput.files[0])
        .subscribe({
          next: (data) => {
            this.currentFile = data;
            this.control!.setValue(JSON.stringify(data));
            $filesInput.value = '';
          },
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  isRequired() {
    return this.control?.hasValidator(Validators.required);
  }

  getInputClasses() {
    return (this.hasErrors() ? 'is-invalid ' : '') + this.inputClass;
  }

  hasErrors() {
    return this.control?.invalid && (this.control?.dirty || this.control?.touched);
  }

  initDatepicker() {
    if (!this.datepicker) {
      return;
    }
    const flatpickrConfig:any = {
      allowInput: true,
      time_24hr: true,
      enableSeconds: true
    };
    if (this.datepicker === 'datepicker') {
      flatpickrConfig.dateFormat = 'Y-m-d';
    } else if (this.datepicker === 'timepicker') {
      flatpickrConfig.enableTime = true;
      flatpickrConfig.noCalendar = true;
      flatpickrConfig.dateFormat = 'H:i:S';
    } else { // datetimepicker
      flatpickrConfig.enableTime = true;
      flatpickrConfig.altInput = true;
      flatpickrConfig.altFormat = 'Y-m-d H:i:S';
      flatpickrConfig.dateFormat = 'Y-m-dTH:i:S';
      // workaround label issue
      flatpickrConfig.onReady = function() {
        const id = this.input.id;
        this.input.id = null;
        this.altInput.id = id;
      };
    }
    const input = this.elRef.nativeElement.querySelector('input');
    const flatpicker = flatpickr(input, flatpickrConfig);
    this.control!.valueChanges.subscribe(val => {
      // update in case value changes after initialization
      flatpicker.setDate(val);
    });
  }

}

<div [formGroup]="group!" class="row mb-3">
    @if (rowType === 'checkbox') {
    <div class="col-md-10 offset-md-2">
        <div class="form-check">
            <input [id]="field" [formControlName]="field" type="checkbox"
                    class="form-check-input {{ getInputClasses() }}" />
            <label [for]="field" class="form-check-label">
                {{ label + (isRequired() ? '*' : '') }}
            </label>
        </div>
        <app-input-errors [control]="control" />
    </div>
    } @else {
    <label [for]="rowType === 'radio' ? '' : field" class="col-md-2 col-form-label">
        {{ label + (isRequired() ? '*' : '') }}
    </label>
    <div class="col-md-10">
        @if (rowType === 'text' || rowType === 'password' || rowType === 'email' || rowType === 'tel') {
        <input [id]="field" [type]="rowType" [formControlName]="field"
                class="form-control {{ getInputClasses() }}" />
        } @else if (rowType === 'number') {
        <input [id]="field" type="number" [formControlName]="field"
                class="form-control {{ getInputClasses() }}" />
        } @else if (rowType === 'textarea') {
        <textarea [id]="field" [formControlName]="field"
                class="form-control {{ getInputClasses() }}"></textarea>
        } @else if (rowType === 'select') {
        <select [id]="field" [formControlName]="field"
                class="form-select {{ getInputClasses() }}">
            <option [ngValue]="null" i18n="@@select.empty.label">Please select</option>
            @for (option of optionsMap | keyvalue; track option.key) {
            <option [ngValue]="option.key">{{ option.value }}</option>
            }
        </select>
        } @else if (rowType === 'multiselect') {
        <select [id]="field" [formControlName]="field" multiple="true"
                class="form-select {{ getInputClasses() }}">
            @for (option of optionsMap | keyvalue; track option.key) {
            <option [ngValue]="option.key">{{ option.value }}</option>
            }
        </select>
        } @else if (rowType === 'radio') {
            @if (!isRequired()) {
            <div class="form-check form-check-inline pt-2">
                <input [id]="field" [formControlName]="field" [value]="null" type="radio"
                       class="form-check-input {{ inputClass }}" />
                <label [for]="field" class="form-check-label" i18n="@@select.empty.label">Please select</label>
            </div>
            }
            @for (option of optionsMap | keyvalue; track option.key) {
            <div class="form-check form-check-inline pt-2">
                <input [id]="field + '_' + option.key" [formControlName]="field" [value]="option.key" type="radio"
                        class="form-check-input {{ getInputClasses() }}" />
                <label [for]="field + '_' + option.key" class="form-check-label">{{ option.value }}</label>
            </div>
            }
        } @else if (rowType === 'file') {
            <input [id]="field" type="hidden" [formControlName]="field" />
            <input [id]="field + '_file'" type="file" (change)="fileChanged($event)"
                   class="form-control {{ currentFile ? 'd-none' : '' }} {{ getInputClasses() }}" />
            @if (currentFile) {
            <div class="form-control-plaintext d-flex align-items-baseline gap-2">
                <span>{{ currentFile.fileName }}</span>
                @if (withDownloads && downloadLink) {
                <a [href]="fileDownloadLink()" target="_blank" class="small text-secondary" i18n="@@file.open">Open</a>
                }
                <span role="button" (click)="fileDelete()" class="small text-secondary text-decoration-underline" i18n="@@file.delete">Delete</span>
            </div>
            }
        }
        <app-input-errors [control]="control" />
    </div>
    }
</div>
