// src/main/webapp/app/address/address-add.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { AddressDTO } from 'app/address/address-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    address: yup.string().emptyToNull().max(255).required(),
    cep: yup.string().emptyToNull().max(20).required(),
    complement: yup.string().emptyToNull().max(255),
    neighbourhood: yup.string().emptyToNull().max(255).required(),
    number: yup.number().integer().emptyToNull(),
    city: yup.string().emptyToNull().max(255).required(),
    uf: yup.string().emptyToNull().max(255).required(),
    user: yup.number().integer().emptyToNull()
  });
}

export default function AddressAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('address.add.headline'));

  const navigate = useNavigate();
  const [userValues, setUserValues] = useState<Map<number,string>>(new Map());

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareRelations = async () => {
    try {
      const userValuesResponse = await axios.get('/api/addresses/userValues');
      setUserValues(userValuesResponse.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareRelations();
  }, []);

  const createAddress = async (data: AddressDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/addresses', data);
      navigate('/addresses', {
            state: {
              msgSuccess: t('address.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('address.add.headline')}</h1>
      <div>
        <Link to="/addresses" className="btn btn-secondary">{t('address.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createAddress)} noValidate>
      <InputRow useFormResult={useFormResult} object="address" field="address" required={true} />
      <InputRow useFormResult={useFormResult} object="address" field="cep" required={true} />
      <InputRow useFormResult={useFormResult} object="address" field="complement" />
      <InputRow useFormResult={useFormResult} object="address" field="neighbourhood" required={true} />
      <InputRow useFormResult={useFormResult} object="address" field="number" type="number" />
      <InputRow useFormResult={useFormResult} object="address" field="city" required={true} />
      <InputRow useFormResult={useFormResult} object="address" field="uf" required={true} />
      <InputRow useFormResult={useFormResult} object="address" field="user" type="select" options={userValues} />
      <input type="submit" value={t('address.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/address/address-add.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { AddressService } from 'app/address/address.service';
import { AddressDTO } from 'app/address/address.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';


@Component({
  selector: 'app-address-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './address-add.component.html'
})
export class AddressAddComponent implements OnInit {

  addressService = inject(AddressService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  userValues?: Map<number,string>;

  addForm = new FormGroup({
    address: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    cep: new FormControl(null, [Validators.required, Validators.maxLength(20)]),
    complement: new FormControl(null, [Validators.maxLength(255)]),
    neighbourhood: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    number: new FormControl(null),
    city: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    uf: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    user: new FormControl(null)
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@address.create.success:Address was created successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.addressService.getUserValues()
        .subscribe({
          next: (data) => this.userValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new AddressDTO(this.addForm.value);
    this.addressService.createAddress(data)
        .subscribe({
          next: () => this.router.navigate(['/addresses'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@address.add.headline">Add Address</h1>
    <div>
        <a routerLink="/addresses" class="btn btn-secondary" i18n="@@address.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="address" i18n-label="@@address.address.label" label="Address" />
    <app-input-row [group]="addForm" field="cep" i18n-label="@@address.cep.label" label="Cep" />
    <app-input-row [group]="addForm" field="complement" i18n-label="@@address.complement.label" label="Complement" />
    <app-input-row [group]="addForm" field="neighbourhood" i18n-label="@@address.neighbourhood.label" label="Neighbourhood" />
    <app-input-row [group]="addForm" field="number" rowType="number" i18n-label="@@address.number.label" label="Number" />
    <app-input-row [group]="addForm" field="city" i18n-label="@@address.city.label" label="City" />
    <app-input-row [group]="addForm" field="uf" i18n-label="@@address.uf.label" label="Uf" />
    <app-input-row [group]="addForm" field="user" rowType="select" [options]="userValues" i18n-label="@@address.user.label" label="User" />
    <input type="submit" i18n-value="@@address.add.headline" value="Add Address" class="btn btn-primary mt-4" />
</form>
