// src/main/webapp/app/address/address-edit.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate, useParams } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { AddressDTO } from 'app/address/address-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    address: yup.string().emptyToNull().max(255).required(),
    cep: yup.string().emptyToNull().max(20).required(),
    complement: yup.string().emptyToNull().max(255),
    neighbourhood: yup.string().emptyToNull().max(255).required(),
    number: yup.number().integer().emptyToNull(),
    city: yup.string().emptyToNull().max(255).required(),
    uf: yup.string().emptyToNull().max(255).required(),
    user: yup.number().integer().emptyToNull()
  });
}

export default function AddressEdit() {
  const { t } = useTranslation();
  useDocumentTitle(t('address.edit.headline'));

  const navigate = useNavigate();
  const [userValues, setUserValues] = useState<Map<number,string>>(new Map());
  const params = useParams();
  const currentId = +params.id!;

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareForm = async () => {
    try {
      const userValuesResponse = await axios.get('/api/addresses/userValues');
      setUserValues(userValuesResponse.data);
      const data = (await axios.get('/api/addresses/' + currentId)).data;
      useFormResult.reset(data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareForm();
  }, []);

  const updateAddress = async (data: AddressDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.put('/api/addresses/' + currentId, data);
      navigate('/addresses', {
            state: {
              msgSuccess: t('address.update.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('address.edit.headline')}</h1>
      <div>
        <Link to="/addresses" className="btn btn-secondary">{t('address.edit.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(updateAddress)} noValidate>
      <InputRow useFormResult={useFormResult} object="address" field="id" disabled={true} type="number" />
      <InputRow useFormResult={useFormResult} object="address" field="address" required={true} />
      <InputRow useFormResult={useFormResult} object="address" field="cep" required={true} />
      <InputRow useFormResult={useFormResult} object="address" field="complement" />
      <InputRow useFormResult={useFormResult} object="address" field="neighbourhood" required={true} />
      <InputRow useFormResult={useFormResult} object="address" field="number" type="number" />
      <InputRow useFormResult={useFormResult} object="address" field="city" required={true} />
      <InputRow useFormResult={useFormResult} object="address" field="uf" required={true} />
      <InputRow useFormResult={useFormResult} object="address" field="user" type="select" options={userValues} />
      <input type="submit" value={t('address.edit.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/address/address-edit.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { AddressService } from 'app/address/address.service';
import { AddressDTO } from 'app/address/address.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { updateForm } from 'app/common/utils';


@Component({
  selector: 'app-address-edit',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './address-edit.component.html'
})
export class AddressEditComponent implements OnInit {

  addressService = inject(AddressService);
  route = inject(ActivatedRoute);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  userValues?: Map<number,string>;
  currentId?: number;

  editForm = new FormGroup({
    id: new FormControl({ value: null, disabled: true }),
    address: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    cep: new FormControl(null, [Validators.required, Validators.maxLength(20)]),
    complement: new FormControl(null, [Validators.maxLength(255)]),
    neighbourhood: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    number: new FormControl(null),
    city: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    uf: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    user: new FormControl(null)
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      updated: $localize`:@@address.update.success:Address was updated successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.currentId = +this.route.snapshot.params['id'];
    this.addressService.getUserValues()
        .subscribe({
          next: (data) => this.userValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.addressService.getAddress(this.currentId!)
        .subscribe({
          next: (data) => updateForm(this.editForm, data),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.editForm.markAllAsTouched();
    if (!this.editForm.valid) {
      return;
    }
    const data = new AddressDTO(this.editForm.value);
    this.addressService.updateAddress(this.currentId!, data)
        .subscribe({
          next: () => this.router.navigate(['/addresses'], {
            state: {
              msgSuccess: this.getMessage('updated')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.editForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@address.edit.headline">Edit Address</h1>
    <div>
        <a routerLink="/addresses" class="btn btn-secondary" i18n="@@address.edit.back">Back to list</a>
    </div>
</div>
<form [formGroup]="editForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="editForm" field="id" rowType="number" i18n-label="@@address.id.label" label="Id" />
    <app-input-row [group]="editForm" field="address" i18n-label="@@address.address.label" label="Address" />
    <app-input-row [group]="editForm" field="cep" i18n-label="@@address.cep.label" label="Cep" />
    <app-input-row [group]="editForm" field="complement" i18n-label="@@address.complement.label" label="Complement" />
    <app-input-row [group]="editForm" field="neighbourhood" i18n-label="@@address.neighbourhood.label" label="Neighbourhood" />
    <app-input-row [group]="editForm" field="number" rowType="number" i18n-label="@@address.number.label" label="Number" />
    <app-input-row [group]="editForm" field="city" i18n-label="@@address.city.label" label="City" />
    <app-input-row [group]="editForm" field="uf" i18n-label="@@address.uf.label" label="Uf" />
    <app-input-row [group]="editForm" field="user" rowType="select" [options]="userValues" i18n-label="@@address.user.label" label="User" />
    <input type="submit" i18n-value="@@address.edit.headline" value="Edit Address" class="btn btn-primary mt-4" />
</form>
