// src/main/webapp/app/address/address-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { AddressService } from 'app/address/address.service';
import { AddressDTO } from 'app/address/address.model';


@Component({
  selector: 'app-address-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './address-list.component.html'})
export class AddressListComponent implements OnInit, OnDestroy {

  addressService = inject(AddressService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  addresses?: AddressDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@address.delete.success:Address was removed successfully.`    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.addressService.getAllAddresses()
        .subscribe({
          next: (data) => this.addresses = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.addressService.deleteAddress(id)
        .subscribe({
          next: () => this.router.navigate(['/addresses'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@address.list.headline">Addresses</h1>
    <div>
        <a routerLink="/addresses/add" class="btn btn-primary ms-2" i18n="@@address.list.createNew">Create new Address</a>
    </div>
</div>
@if (!addresses || addresses.length === 0) {
<div i18n="@@address.list.empty">No Addresses could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@address.id.label">Id</th>
                <th scope="col" i18n="@@address.address.label">Address</th>
                <th scope="col" i18n="@@address.cep.label">Cep</th>
                <th scope="col" i18n="@@address.complement.label">Complement</th>
                <th scope="col" i18n="@@address.neighbourhood.label">Neighbourhood</th>
                <th scope="col" i18n="@@address.number.label">Number</th>
                <th scope="col" i18n="@@address.city.label">City</th>
                <th scope="col" i18n="@@address.uf.label">Uf</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (address of addresses; track address.id) {
            <tr>
                <td>{{ address.id }}</td>
                <td>{{ address.address }}</td>
                <td>{{ address.cep }}</td>
                <td>{{ address.complement }}</td>
                <td>{{ address.neighbourhood }}</td>
                <td>{{ address.number }}</td>
                <td>{{ address.city }}</td>
                <td>{{ address.uf }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/addresses/edit', address.id]" class="btn btn-sm btn-secondary" i18n="@@address.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(address.id!)" class="btn btn-sm btn-secondary" i18n="@@address.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}

// src/main/webapp/app/address/address-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { AddressDTO } from 'app/address/address-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function AddressList() {
  const { t } = useTranslation();
  useDocumentTitle(t('address.list.headline'));

  const [addresses, setAddresses] = useState<AddressDTO[]>([]);
  const navigate = useNavigate();

  const getAllAddresses = async () => {
    try {
      const response = await axios.get('/api/addresses');
      setAddresses(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/addresses/' + id);
      navigate('/addresses', {
            state: {
              msgInfo: t('address.delete.success')
            }
          });
      getAllAddresses();
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllAddresses();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('address.list.headline')}</h1>
      <div>
        <Link to="/addresses/add" className="btn btn-primary ms-2">{t('address.list.createNew')}</Link>
      </div>
    </div>
    {!addresses || addresses.length === 0 ? (
    <div>{t('address.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('address.id.label')}</th>
            <th scope="col">{t('address.address.label')}</th>
            <th scope="col">{t('address.cep.label')}</th>
            <th scope="col">{t('address.complement.label')}</th>
            <th scope="col">{t('address.neighbourhood.label')}</th>
            <th scope="col">{t('address.number.label')}</th>
            <th scope="col">{t('address.city.label')}</th>
            <th scope="col">{t('address.uf.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {addresses.map((address) => (
          <tr key={address.id}>
            <td>{address.id}</td>
            <td>{address.address}</td>
            <td>{address.cep}</td>
            <td>{address.complement}</td>
            <td>{address.neighbourhood}</td>
            <td>{address.number}</td>
            <td>{address.city}</td>
            <td>{address.uf}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/addresses/edit/' + address.id} className="btn btn-sm btn-secondary">{t('address.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(address.id!)} className="btn btn-sm btn-secondary">{t('address.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}
