// src/main/webapp/app/alert/alert-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { AlertService } from 'app/alert/alert.service';
import { AlertDTO } from 'app/alert/alert.model';


@Component({
  selector: 'app-alert-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './alert-list.component.html'})
export class AlertListComponent implements OnInit, OnDestroy {

  alertService = inject(AlertService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  alerts?: AlertDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@alert.delete.success:Alert was removed successfully.`    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.alertService.getAllAlerts()
        .subscribe({
          next: (data) => this.alerts = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.alertService.deleteAlert(id)
        .subscribe({
          next: () => this.router.navigate(['/alerts'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@alert.list.headline">Alerts</h1>
    <div>
        <a routerLink="/alerts/add" class="btn btn-primary ms-2" i18n="@@alert.list.createNew">Create new Alert</a>
    </div>
</div>
@if (!alerts || alerts.length === 0) {
<div i18n="@@alert.list.empty">No Alerts could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@alert.id.label">Id</th>
                <th scope="col" i18n="@@alert.expirationTime.label">Expiration Time</th>
                <th scope="col" i18n="@@alert.active.label">Active</th>
                <th scope="col" i18n="@@alert.alertType.label">Alert Type</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (alert of alerts; track alert.id) {
            <tr>
                <td>{{ alert.id }}</td>
                <td>{{ alert.expirationTime }}</td>
                <td>{{ alert.active }}</td>
                <td>{{ alert.alertType }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/alerts/edit', alert.id]" class="btn btn-sm btn-secondary" i18n="@@alert.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(alert.id!)" class="btn btn-sm btn-secondary" i18n="@@alert.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}

// src/main/webapp/app/alert/alert-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { AlertDTO } from 'app/alert/alert-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function AlertList() {
  const { t } = useTranslation();
  useDocumentTitle(t('alert.list.headline'));

  const [alerts, setAlerts] = useState<AlertDTO[]>([]);
  const navigate = useNavigate();

  const getAllAlerts = async () => {
    try {
      const response = await axios.get('/api/alerts');
      setAlerts(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/alerts/' + id);
      navigate('/alerts', {
            state: {
              msgInfo: t('alert.delete.success')
            }
          });
      getAllAlerts();
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllAlerts();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('alert.list.headline')}</h1>
      <div>
        <Link to="/alerts/add" className="btn btn-primary ms-2">{t('alert.list.createNew')}</Link>
      </div>
    </div>
    {!alerts || alerts.length === 0 ? (
    <div>{t('alert.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('alert.id.label')}</th>
            <th scope="col">{t('alert.expirationTime.label')}</th>
            <th scope="col">{t('alert.active.label')}</th>
            <th scope="col">{t('alert.alertType.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {alerts.map((alert) => (
          <tr key={alert.id}>
            <td>{alert.id}</td>
            <td>{alert.expirationTime}</td>
            <td>{alert.active?.toString()}</td>
            <td>{alert.alertType}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/alerts/edit/' + alert.id} className="btn btn-sm btn-secondary">{t('alert.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(alert.id!)} className="btn btn-sm btn-secondary">{t('alert.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}
