// src/main/webapp/app/alert/alert-add.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { AlertDTO } from 'app/alert/alert-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    description: yup.string().emptyToNull().required(),
    expirationTime: yup.string().emptyToNull().required(),
    active: yup.bool(),
    alertType: yup.string().emptyToNull().max(255)
  });
}

export default function AlertAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('alert.add.headline'));

  const navigate = useNavigate();

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const createAlert = async (data: AlertDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/alerts', data);
      navigate('/alerts', {
            state: {
              msgSuccess: t('alert.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('alert.add.headline')}</h1>
      <div>
        <Link to="/alerts" className="btn btn-secondary">{t('alert.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createAlert)} noValidate>
      <InputRow useFormResult={useFormResult} object="alert" field="description" required={true} type="textarea" />
      <InputRow useFormResult={useFormResult} object="alert" field="expirationTime" required={true} type="datetimepicker" />
      <InputRow useFormResult={useFormResult} object="alert" field="active" type="checkbox" />
      <InputRow useFormResult={useFormResult} object="alert" field="alertType" />
      <input type="submit" value={t('alert.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/alert/alert-add.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { AlertService } from 'app/alert/alert.service';
import { AlertDTO } from 'app/alert/alert.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';


@Component({
  selector: 'app-alert-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './alert-add.component.html'
})
export class AlertAddComponent {

  alertService = inject(AlertService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  addForm = new FormGroup({
    description: new FormControl(null, [Validators.required]),
    expirationTime: new FormControl(null, [Validators.required]),
    active: new FormControl(false),
    alertType: new FormControl(null, [Validators.maxLength(255)])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@alert.create.success:Alert was created successfully.`
    };
    return messages[key];
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new AlertDTO(this.addForm.value);
    this.alertService.createAlert(data)
        .subscribe({
          next: () => this.router.navigate(['/alerts'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@alert.add.headline">Add Alert</h1>
    <div>
        <a routerLink="/alerts" class="btn btn-secondary" i18n="@@alert.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="description" rowType="textarea" i18n-label="@@alert.description.label" label="Description" />
    <app-input-row [group]="addForm" field="expirationTime" rowType="datetimepicker" i18n-label="@@alert.expirationTime.label" label="Expiration Time" />
    <app-input-row [group]="addForm" field="active" rowType="checkbox" i18n-label="@@alert.active.label" label="Active" />
    <app-input-row [group]="addForm" field="alertType" i18n-label="@@alert.alertType.label" label="Alert Type" />
    <input type="submit" i18n-value="@@alert.add.headline" value="Add Alert" class="btn btn-primary mt-4" />
</form>
