// src/main/webapp/app/alert/alert-edit.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { AlertService } from 'app/alert/alert.service';
import { AlertDTO } from 'app/alert/alert.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { updateForm } from 'app/common/utils';


@Component({
  selector: 'app-alert-edit',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './alert-edit.component.html'
})
export class AlertEditComponent implements OnInit {

  alertService = inject(AlertService);
  route = inject(ActivatedRoute);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  currentId?: number;

  editForm = new FormGroup({
    id: new FormControl({ value: null, disabled: true }),
    description: new FormControl(null, [Validators.required]),
    expirationTime: new FormControl(null, [Validators.required]),
    active: new FormControl(false),
    alertType: new FormControl(null, [Validators.maxLength(255)])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      updated: $localize`:@@alert.update.success:Alert was updated successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.currentId = +this.route.snapshot.params['id'];
    this.alertService.getAlert(this.currentId!)
        .subscribe({
          next: (data) => updateForm(this.editForm, data),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.editForm.markAllAsTouched();
    if (!this.editForm.valid) {
      return;
    }
    const data = new AlertDTO(this.editForm.value);
    this.alertService.updateAlert(this.currentId!, data)
        .subscribe({
          next: () => this.router.navigate(['/alerts'], {
            state: {
              msgSuccess: this.getMessage('updated')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.editForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@alert.edit.headline">Edit Alert</h1>
    <div>
        <a routerLink="/alerts" class="btn btn-secondary" i18n="@@alert.edit.back">Back to list</a>
    </div>
</div>
<form [formGroup]="editForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="editForm" field="id" rowType="number" i18n-label="@@alert.id.label" label="Id" />
    <app-input-row [group]="editForm" field="description" rowType="textarea" i18n-label="@@alert.description.label" label="Description" />
    <app-input-row [group]="editForm" field="expirationTime" rowType="datetimepicker" i18n-label="@@alert.expirationTime.label" label="Expiration Time" />
    <app-input-row [group]="editForm" field="active" rowType="checkbox" i18n-label="@@alert.active.label" label="Active" />
    <app-input-row [group]="editForm" field="alertType" i18n-label="@@alert.alertType.label" label="Alert Type" />
    <input type="submit" i18n-value="@@alert.edit.headline" value="Edit Alert" class="btn btn-primary mt-4" />
</form>

// src/main/webapp/app/alert/alert-edit.tsx
import React, { useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate, useParams } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { AlertDTO } from 'app/alert/alert-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    description: yup.string().emptyToNull().required(),
    expirationTime: yup.string().emptyToNull().required(),
    active: yup.bool(),
    alertType: yup.string().emptyToNull().max(255)
  });
}

export default function AlertEdit() {
  const { t } = useTranslation();
  useDocumentTitle(t('alert.edit.headline'));

  const navigate = useNavigate();
  const params = useParams();
  const currentId = +params.id!;

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareForm = async () => {
    try {
      const data = (await axios.get('/api/alerts/' + currentId)).data;
      useFormResult.reset(data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareForm();
  }, []);

  const updateAlert = async (data: AlertDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.put('/api/alerts/' + currentId, data);
      navigate('/alerts', {
            state: {
              msgSuccess: t('alert.update.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('alert.edit.headline')}</h1>
      <div>
        <Link to="/alerts" className="btn btn-secondary">{t('alert.edit.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(updateAlert)} noValidate>
      <InputRow useFormResult={useFormResult} object="alert" field="id" disabled={true} type="number" />
      <InputRow useFormResult={useFormResult} object="alert" field="description" required={true} type="textarea" />
      <InputRow useFormResult={useFormResult} object="alert" field="expirationTime" required={true} type="datetimepicker" />
      <InputRow useFormResult={useFormResult} object="alert" field="active" type="checkbox" />
      <InputRow useFormResult={useFormResult} object="alert" field="alertType" />
      <input type="submit" value={t('alert.edit.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}
