// src/main/webapp/app/health-insurance/health-insurance-edit.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { HealthInsuranceService } from 'app/health-insurance/health-insurance.service';
import { HealthInsuranceDTO } from 'app/health-insurance/health-insurance.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { updateForm } from 'app/common/utils';


@Component({
  selector: 'app-health-insurance-edit',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './health-insurance-edit.component.html'
})
export class HealthInsuranceEditComponent implements OnInit {

  healthInsuranceService = inject(HealthInsuranceService);
  route = inject(ActivatedRoute);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  documentsValues?: Map<number,string>;
  currentId?: number;

  editForm = new FormGroup({
    id: new FormControl({ value: null, disabled: true }),
    number: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    type: new FormControl(null, [Validators.maxLength(255)]),
    plan: new FormControl(null, [Validators.maxLength(255)]),
    carrier: new FormControl(null, [Validators.maxLength(255)]),
    active: new FormControl(false),
    documents: new FormControl([])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      updated: $localize`:@@healthInsurance.update.success:Health Insurance was updated successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.currentId = +this.route.snapshot.params['id'];
    this.healthInsuranceService.getDocumentsValues()
        .subscribe({
          next: (data) => this.documentsValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.healthInsuranceService.getHealthInsurance(this.currentId!)
        .subscribe({
          next: (data) => updateForm(this.editForm, data),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.editForm.markAllAsTouched();
    if (!this.editForm.valid) {
      return;
    }
    const data = new HealthInsuranceDTO(this.editForm.value);
    this.healthInsuranceService.updateHealthInsurance(this.currentId!, data)
        .subscribe({
          next: () => this.router.navigate(['/healthInsurances'], {
            state: {
              msgSuccess: this.getMessage('updated')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.editForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@healthInsurance.edit.headline">Edit Health Insurance</h1>
    <div>
        <a routerLink="/healthInsurances" class="btn btn-secondary" i18n="@@healthInsurance.edit.back">Back to list</a>
    </div>
</div>
<form [formGroup]="editForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="editForm" field="id" rowType="number" i18n-label="@@healthInsurance.id.label" label="Id" />
    <app-input-row [group]="editForm" field="number" i18n-label="@@healthInsurance.number.label" label="Number" />
    <app-input-row [group]="editForm" field="type" i18n-label="@@healthInsurance.type.label" label="Type" />
    <app-input-row [group]="editForm" field="plan" i18n-label="@@healthInsurance.plan.label" label="Plan" />
    <app-input-row [group]="editForm" field="carrier" i18n-label="@@healthInsurance.carrier.label" label="Carrier" />
    <app-input-row [group]="editForm" field="active" rowType="checkbox" i18n-label="@@healthInsurance.active.label" label="Active" />
    <app-input-row [group]="editForm" field="documents" rowType="multiselect" [options]="documentsValues" i18n-label="@@healthInsurance.documents.label" label="Documents" />
    <input type="submit" i18n-value="@@healthInsurance.edit.headline" value="Edit Health Insurance" class="btn btn-primary mt-4" />
</form>

// src/main/webapp/app/health-insurance/health-insurance-edit.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate, useParams } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { HealthInsuranceDTO } from 'app/health-insurance/health-insurance-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    number: yup.string().emptyToNull().max(255).required(),
    type: yup.string().emptyToNull().max(255),
    plan: yup.string().emptyToNull().max(255),
    carrier: yup.string().emptyToNull().max(255),
    active: yup.bool(),
    documents: yup.array(yup.number().required()).emptyToNull().json()
  });
}

export default function HealthInsuranceEdit() {
  const { t } = useTranslation();
  useDocumentTitle(t('healthInsurance.edit.headline'));

  const navigate = useNavigate();
  const [documentsValues, setDocumentsValues] = useState<Map<number,string>>(new Map());
  const params = useParams();
  const currentId = +params.id!;

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareForm = async () => {
    try {
      const documentsValuesResponse = await axios.get('/api/healthInsurances/documentsValues');
      setDocumentsValues(documentsValuesResponse.data);
      const data = (await axios.get('/api/healthInsurances/' + currentId)).data;
      if (data.documents) {
        data.documents = JSON.stringify(data.documents, undefined, 2);
      }
      useFormResult.reset(data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareForm();
  }, []);

  const updateHealthInsurance = async (data: HealthInsuranceDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.put('/api/healthInsurances/' + currentId, data);
      navigate('/healthInsurances', {
            state: {
              msgSuccess: t('healthInsurance.update.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('healthInsurance.edit.headline')}</h1>
      <div>
        <Link to="/healthInsurances" className="btn btn-secondary">{t('healthInsurance.edit.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(updateHealthInsurance)} noValidate>
      <InputRow useFormResult={useFormResult} object="healthInsurance" field="id" disabled={true} type="number" />
      <InputRow useFormResult={useFormResult} object="healthInsurance" field="number" required={true} />
      <InputRow useFormResult={useFormResult} object="healthInsurance" field="type" />
      <InputRow useFormResult={useFormResult} object="healthInsurance" field="plan" />
      <InputRow useFormResult={useFormResult} object="healthInsurance" field="carrier" />
      <InputRow useFormResult={useFormResult} object="healthInsurance" field="active" type="checkbox" />
      <InputRow useFormResult={useFormResult} object="healthInsurance" field="documents" type="multiselect" options={documentsValues} />
      <input type="submit" value={t('healthInsurance.edit.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}
