// src/main/webapp/app/health-insurance/health-insurance-add.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { HealthInsuranceService } from 'app/health-insurance/health-insurance.service';
import { HealthInsuranceDTO } from 'app/health-insurance/health-insurance.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';


@Component({
  selector: 'app-health-insurance-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './health-insurance-add.component.html'
})
export class HealthInsuranceAddComponent implements OnInit {

  healthInsuranceService = inject(HealthInsuranceService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  documentsValues?: Map<number,string>;

  addForm = new FormGroup({
    number: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    type: new FormControl(null, [Validators.maxLength(255)]),
    plan: new FormControl(null, [Validators.maxLength(255)]),
    carrier: new FormControl(null, [Validators.maxLength(255)]),
    active: new FormControl(false),
    documents: new FormControl([])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@healthInsurance.create.success:Health Insurance was created successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.healthInsuranceService.getDocumentsValues()
        .subscribe({
          next: (data) => this.documentsValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new HealthInsuranceDTO(this.addForm.value);
    this.healthInsuranceService.createHealthInsurance(data)
        .subscribe({
          next: () => this.router.navigate(['/healthInsurances'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@healthInsurance.add.headline">Add Health Insurance</h1>
    <div>
        <a routerLink="/healthInsurances" class="btn btn-secondary" i18n="@@healthInsurance.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="number" i18n-label="@@healthInsurance.number.label" label="Number" />
    <app-input-row [group]="addForm" field="type" i18n-label="@@healthInsurance.type.label" label="Type" />
    <app-input-row [group]="addForm" field="plan" i18n-label="@@healthInsurance.plan.label" label="Plan" />
    <app-input-row [group]="addForm" field="carrier" i18n-label="@@healthInsurance.carrier.label" label="Carrier" />
    <app-input-row [group]="addForm" field="active" rowType="checkbox" i18n-label="@@healthInsurance.active.label" label="Active" />
    <app-input-row [group]="addForm" field="documents" rowType="multiselect" [options]="documentsValues" i18n-label="@@healthInsurance.documents.label" label="Documents" />
    <input type="submit" i18n-value="@@healthInsurance.add.headline" value="Add Health Insurance" class="btn btn-primary mt-4" />
</form>

// src/main/webapp/app/health-insurance/health-insurance-add.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { HealthInsuranceDTO } from 'app/health-insurance/health-insurance-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    number: yup.string().emptyToNull().max(255).required(),
    type: yup.string().emptyToNull().max(255),
    plan: yup.string().emptyToNull().max(255),
    carrier: yup.string().emptyToNull().max(255),
    active: yup.bool(),
    documents: yup.array(yup.number().required()).emptyToNull().json()
  });
}

export default function HealthInsuranceAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('healthInsurance.add.headline'));

  const navigate = useNavigate();
  const [documentsValues, setDocumentsValues] = useState<Map<number,string>>(new Map());

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareRelations = async () => {
    try {
      const documentsValuesResponse = await axios.get('/api/healthInsurances/documentsValues');
      setDocumentsValues(documentsValuesResponse.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareRelations();
  }, []);

  const createHealthInsurance = async (data: HealthInsuranceDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/healthInsurances', data);
      navigate('/healthInsurances', {
            state: {
              msgSuccess: t('healthInsurance.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('healthInsurance.add.headline')}</h1>
      <div>
        <Link to="/healthInsurances" className="btn btn-secondary">{t('healthInsurance.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createHealthInsurance)} noValidate>
      <InputRow useFormResult={useFormResult} object="healthInsurance" field="number" required={true} />
      <InputRow useFormResult={useFormResult} object="healthInsurance" field="type" />
      <InputRow useFormResult={useFormResult} object="healthInsurance" field="plan" />
      <InputRow useFormResult={useFormResult} object="healthInsurance" field="carrier" />
      <InputRow useFormResult={useFormResult} object="healthInsurance" field="active" type="checkbox" />
      <InputRow useFormResult={useFormResult} object="healthInsurance" field="documents" type="multiselect" options={documentsValues} />
      <input type="submit" value={t('healthInsurance.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}
