// src/main/webapp/app/health-insurance/health-insurance-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { HealthInsuranceService } from 'app/health-insurance/health-insurance.service';
import { HealthInsuranceDTO } from 'app/health-insurance/health-insurance.model';


@Component({
  selector: 'app-health-insurance-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './health-insurance-list.component.html'})
export class HealthInsuranceListComponent implements OnInit, OnDestroy {

  healthInsuranceService = inject(HealthInsuranceService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  healthInsurances?: HealthInsuranceDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@healthInsurance.delete.success:Health Insurance was removed successfully.`    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.healthInsuranceService.getAllHealthInsurances()
        .subscribe({
          next: (data) => this.healthInsurances = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.healthInsuranceService.deleteHealthInsurance(id)
        .subscribe({
          next: () => this.router.navigate(['/healthInsurances'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@healthInsurance.list.headline">Health Insurances</h1>
    <div>
        <a routerLink="/healthInsurances/add" class="btn btn-primary ms-2" i18n="@@healthInsurance.list.createNew">Create new Health Insurance</a>
    </div>
</div>
@if (!healthInsurances || healthInsurances.length === 0) {
<div i18n="@@healthInsurance.list.empty">No Health Insurances could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@healthInsurance.id.label">Id</th>
                <th scope="col" i18n="@@healthInsurance.number.label">Number</th>
                <th scope="col" i18n="@@healthInsurance.type.label">Type</th>
                <th scope="col" i18n="@@healthInsurance.plan.label">Plan</th>
                <th scope="col" i18n="@@healthInsurance.carrier.label">Carrier</th>
                <th scope="col" i18n="@@healthInsurance.active.label">Active</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (healthInsurance of healthInsurances; track healthInsurance.id) {
            <tr>
                <td>{{ healthInsurance.id }}</td>
                <td>{{ healthInsurance.number }}</td>
                <td>{{ healthInsurance.type }}</td>
                <td>{{ healthInsurance.plan }}</td>
                <td>{{ healthInsurance.carrier }}</td>
                <td>{{ healthInsurance.active }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/healthInsurances/edit', healthInsurance.id]" class="btn btn-sm btn-secondary" i18n="@@healthInsurance.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(healthInsurance.id!)" class="btn btn-sm btn-secondary" i18n="@@healthInsurance.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}

// src/main/webapp/app/health-insurance/health-insurance-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { HealthInsuranceDTO } from 'app/health-insurance/health-insurance-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function HealthInsuranceList() {
  const { t } = useTranslation();
  useDocumentTitle(t('healthInsurance.list.headline'));

  const [healthInsurances, setHealthInsurances] = useState<HealthInsuranceDTO[]>([]);
  const navigate = useNavigate();

  const getAllHealthInsurances = async () => {
    try {
      const response = await axios.get('/api/healthInsurances');
      setHealthInsurances(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/healthInsurances/' + id);
      navigate('/healthInsurances', {
            state: {
              msgInfo: t('healthInsurance.delete.success')
            }
          });
      getAllHealthInsurances();
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllHealthInsurances();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('healthInsurance.list.headline')}</h1>
      <div>
        <Link to="/healthInsurances/add" className="btn btn-primary ms-2">{t('healthInsurance.list.createNew')}</Link>
      </div>
    </div>
    {!healthInsurances || healthInsurances.length === 0 ? (
    <div>{t('healthInsurance.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('healthInsurance.id.label')}</th>
            <th scope="col">{t('healthInsurance.number.label')}</th>
            <th scope="col">{t('healthInsurance.type.label')}</th>
            <th scope="col">{t('healthInsurance.plan.label')}</th>
            <th scope="col">{t('healthInsurance.carrier.label')}</th>
            <th scope="col">{t('healthInsurance.active.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {healthInsurances.map((healthInsurance) => (
          <tr key={healthInsurance.id}>
            <td>{healthInsurance.id}</td>
            <td>{healthInsurance.number}</td>
            <td>{healthInsurance.type}</td>
            <td>{healthInsurance.plan}</td>
            <td>{healthInsurance.carrier}</td>
            <td>{healthInsurance.active?.toString()}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/healthInsurances/edit/' + healthInsurance.id} className="btn btn-sm btn-secondary">{t('healthInsurance.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(healthInsurance.id!)} className="btn btn-sm btn-secondary">{t('healthInsurance.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}
