// src/main/webapp/app/phones/phones-add.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { PhonesDTO } from 'app/phones/phones-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    ddd: yup.string().emptyToNull().max(4),
    number: yup.string().emptyToNull().max(40),
    user: yup.number().integer().emptyToNull()
  });
}

export default function PhonesAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('phones.add.headline'));

  const navigate = useNavigate();
  const [userValues, setUserValues] = useState<Map<number,string>>(new Map());

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareRelations = async () => {
    try {
      const userValuesResponse = await axios.get('/api/phoness/userValues');
      setUserValues(userValuesResponse.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareRelations();
  }, []);

  const createPhones = async (data: PhonesDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/phoness', data);
      navigate('/phoness', {
            state: {
              msgSuccess: t('phones.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('phones.add.headline')}</h1>
      <div>
        <Link to="/phoness" className="btn btn-secondary">{t('phones.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createPhones)} noValidate>
      <InputRow useFormResult={useFormResult} object="phones" field="ddd" />
      <InputRow useFormResult={useFormResult} object="phones" field="number" />
      <InputRow useFormResult={useFormResult} object="phones" field="user" type="select" options={userValues} />
      <input type="submit" value={t('phones.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/phones/phones-add.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { PhonesService } from 'app/phones/phones.service';
import { PhonesDTO } from 'app/phones/phones.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';


@Component({
  selector: 'app-phones-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './phones-add.component.html'
})
export class PhonesAddComponent implements OnInit {

  phonesService = inject(PhonesService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  userValues?: Map<number,string>;

  addForm = new FormGroup({
    ddd: new FormControl(null, [Validators.maxLength(4)]),
    number: new FormControl(null, [Validators.maxLength(40)]),
    user: new FormControl(null)
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@phones.create.success:Phones was created successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.phonesService.getUserValues()
        .subscribe({
          next: (data) => this.userValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new PhonesDTO(this.addForm.value);
    this.phonesService.createPhones(data)
        .subscribe({
          next: () => this.router.navigate(['/phoness'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@phones.add.headline">Add Phones</h1>
    <div>
        <a routerLink="/phoness" class="btn btn-secondary" i18n="@@phones.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="ddd" i18n-label="@@phones.ddd.label" label="Ddd" />
    <app-input-row [group]="addForm" field="number" i18n-label="@@phones.number.label" label="Number" />
    <app-input-row [group]="addForm" field="user" rowType="select" [options]="userValues" i18n-label="@@phones.user.label" label="User" />
    <input type="submit" i18n-value="@@phones.add.headline" value="Add Phones" class="btn btn-primary mt-4" />
</form>
