// src/main/webapp/app/phones/phones-edit.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { PhonesService } from 'app/phones/phones.service';
import { PhonesDTO } from 'app/phones/phones.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { updateForm } from 'app/common/utils';


@Component({
  selector: 'app-phones-edit',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './phones-edit.component.html'
})
export class PhonesEditComponent implements OnInit {

  phonesService = inject(PhonesService);
  route = inject(ActivatedRoute);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  userValues?: Map<number,string>;
  currentId?: number;

  editForm = new FormGroup({
    id: new FormControl({ value: null, disabled: true }),
    ddd: new FormControl(null, [Validators.maxLength(4)]),
    number: new FormControl(null, [Validators.maxLength(40)]),
    user: new FormControl(null)
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      updated: $localize`:@@phones.update.success:Phones was updated successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.currentId = +this.route.snapshot.params['id'];
    this.phonesService.getUserValues()
        .subscribe({
          next: (data) => this.userValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.phonesService.getPhones(this.currentId!)
        .subscribe({
          next: (data) => updateForm(this.editForm, data),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.editForm.markAllAsTouched();
    if (!this.editForm.valid) {
      return;
    }
    const data = new PhonesDTO(this.editForm.value);
    this.phonesService.updatePhones(this.currentId!, data)
        .subscribe({
          next: () => this.router.navigate(['/phoness'], {
            state: {
              msgSuccess: this.getMessage('updated')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.editForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@phones.edit.headline">Edit Phones</h1>
    <div>
        <a routerLink="/phoness" class="btn btn-secondary" i18n="@@phones.edit.back">Back to list</a>
    </div>
</div>
<form [formGroup]="editForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="editForm" field="id" rowType="number" i18n-label="@@phones.id.label" label="Id" />
    <app-input-row [group]="editForm" field="ddd" i18n-label="@@phones.ddd.label" label="Ddd" />
    <app-input-row [group]="editForm" field="number" i18n-label="@@phones.number.label" label="Number" />
    <app-input-row [group]="editForm" field="user" rowType="select" [options]="userValues" i18n-label="@@phones.user.label" label="User" />
    <input type="submit" i18n-value="@@phones.edit.headline" value="Edit Phones" class="btn btn-primary mt-4" />
</form>

// src/main/webapp/app/phones/phones-edit.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate, useParams } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { PhonesDTO } from 'app/phones/phones-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    ddd: yup.string().emptyToNull().max(4),
    number: yup.string().emptyToNull().max(40),
    user: yup.number().integer().emptyToNull()
  });
}

export default function PhonesEdit() {
  const { t } = useTranslation();
  useDocumentTitle(t('phones.edit.headline'));

  const navigate = useNavigate();
  const [userValues, setUserValues] = useState<Map<number,string>>(new Map());
  const params = useParams();
  const currentId = +params.id!;

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareForm = async () => {
    try {
      const userValuesResponse = await axios.get('/api/phoness/userValues');
      setUserValues(userValuesResponse.data);
      const data = (await axios.get('/api/phoness/' + currentId)).data;
      useFormResult.reset(data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareForm();
  }, []);

  const updatePhones = async (data: PhonesDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.put('/api/phoness/' + currentId, data);
      navigate('/phoness', {
            state: {
              msgSuccess: t('phones.update.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('phones.edit.headline')}</h1>
      <div>
        <Link to="/phoness" className="btn btn-secondary">{t('phones.edit.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(updatePhones)} noValidate>
      <InputRow useFormResult={useFormResult} object="phones" field="id" disabled={true} type="number" />
      <InputRow useFormResult={useFormResult} object="phones" field="ddd" />
      <InputRow useFormResult={useFormResult} object="phones" field="number" />
      <InputRow useFormResult={useFormResult} object="phones" field="user" type="select" options={userValues} />
      <input type="submit" value={t('phones.edit.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}
