// src/main/webapp/app/phones/phones-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { PhonesDTO } from 'app/phones/phones-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function PhonesList() {
  const { t } = useTranslation();
  useDocumentTitle(t('phones.list.headline'));

  const [phoneses, setPhoneses] = useState<PhonesDTO[]>([]);
  const navigate = useNavigate();

  const getAllPhoneses = async () => {
    try {
      const response = await axios.get('/api/phoness');
      setPhoneses(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/phoness/' + id);
      navigate('/phoness', {
            state: {
              msgInfo: t('phones.delete.success')
            }
          });
      getAllPhoneses();
    } catch (error: any) {
      if (error?.response?.data?.code === 'REFERENCED') {
        const messageParts = error.response.data.message.split(',');
        navigate('/phoness', {
              state: {
                msgError: t(messageParts[0]!, { id: messageParts[1]! })
              }
            });
        return;
      }
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllPhoneses();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('phones.list.headline')}</h1>
      <div>
        <Link to="/phoness/add" className="btn btn-primary ms-2">{t('phones.list.createNew')}</Link>
      </div>
    </div>
    {!phoneses || phoneses.length === 0 ? (
    <div>{t('phones.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('phones.id.label')}</th>
            <th scope="col">{t('phones.ddd.label')}</th>
            <th scope="col">{t('phones.number.label')}</th>
            <th scope="col">{t('phones.user.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {phoneses.map((phones) => (
          <tr key={phones.id}>
            <td>{phones.id}</td>
            <td>{phones.ddd}</td>
            <td>{phones.number}</td>
            <td>{phones.user}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/phoness/edit/' + phones.id} className="btn btn-sm btn-secondary">{t('phones.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(phones.id!)} className="btn btn-sm btn-secondary">{t('phones.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}

// src/main/webapp/app/phones/phones-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { PhonesService } from 'app/phones/phones.service';
import { PhonesDTO } from 'app/phones/phones.model';


@Component({
  selector: 'app-phones-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './phones-list.component.html'})
export class PhonesListComponent implements OnInit, OnDestroy {

  phonesService = inject(PhonesService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  phoneses?: PhonesDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@phones.delete.success:Phones was removed successfully.`,
      'phones.responsible.phones.referenced': $localize`:@@phones.responsible.phones.referenced:This entity is still referenced by Responsible ${details?.id} via field Phones.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.phonesService.getAllPhoneses()
        .subscribe({
          next: (data) => this.phoneses = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.phonesService.deletePhones(id)
        .subscribe({
          next: () => this.router.navigate(['/phoness'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => {
            if (error.error?.code === 'REFERENCED') {
              const messageParts = error.error.message.split(',');
              this.router.navigate(['/phoness'], {
                state: {
                  msgError: this.getMessage(messageParts[0], { id: messageParts[1] })
                }
              });
              return;
            }
            this.errorHandler.handleServerError(error.error)
          }
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@phones.list.headline">Phoneses</h1>
    <div>
        <a routerLink="/phoness/add" class="btn btn-primary ms-2" i18n="@@phones.list.createNew">Create new Phones</a>
    </div>
</div>
@if (!phoneses || phoneses.length === 0) {
<div i18n="@@phones.list.empty">No Phoneses could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@phones.id.label">Id</th>
                <th scope="col" i18n="@@phones.ddd.label">Ddd</th>
                <th scope="col" i18n="@@phones.number.label">Number</th>
                <th scope="col" i18n="@@phones.user.label">User</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (phones of phoneses; track phones.id) {
            <tr>
                <td>{{ phones.id }}</td>
                <td>{{ phones.ddd }}</td>
                <td>{{ phones.number }}</td>
                <td>{{ phones.user }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/phoness/edit', phones.id]" class="btn btn-sm btn-secondary" i18n="@@phones.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(phones.id!)" class="btn btn-sm btn-secondary" i18n="@@phones.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}
