// src/main/webapp/app/user/user-edit.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { UserService } from 'app/user/user.service';
import { UserDTO } from 'app/user/user.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { updateForm } from 'app/common/utils';


@Component({
  selector: 'app-user-edit',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './user-edit.component.html'
})
export class UserEditComponent implements OnInit {

  userService = inject(UserService);
  route = inject(ActivatedRoute);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  roleValues?: Map<number,string>;
  currentId?: number;

  editForm = new FormGroup({
    id: new FormControl({ value: null, disabled: true }),
    email: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    password: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    fullname: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    active: new FormControl(false),
    socialname: new FormControl(null, [Validators.maxLength(255)]),
    cpf: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    crm: new FormControl(null, [Validators.maxLength(255)]),
    countAccess: new FormControl(null),
    role: new FormControl(null)
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      updated: $localize`:@@user.update.success:User was updated successfully.`,
      USER_EMAIL_UNIQUE: $localize`:@@Exists.user.email:This Email is already taken.`,
      USER_CPF_UNIQUE: $localize`:@@Exists.user.cpf:This Cpf is already taken.`,
      USER_ROLE_UNIQUE: $localize`:@@Exists.user.role:This Role is already referenced by another User.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.currentId = +this.route.snapshot.params['id'];
    this.userService.getRoleValues()
        .subscribe({
          next: (data) => this.roleValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.userService.getUser(this.currentId!)
        .subscribe({
          next: (data) => updateForm(this.editForm, data),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.editForm.markAllAsTouched();
    if (!this.editForm.valid) {
      return;
    }
    const data = new UserDTO(this.editForm.value);
    this.userService.updateUser(this.currentId!, data)
        .subscribe({
          next: () => this.router.navigate(['/users'], {
            state: {
              msgSuccess: this.getMessage('updated')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.editForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@user.edit.headline">Edit User</h1>
    <div>
        <a routerLink="/users" class="btn btn-secondary" i18n="@@user.edit.back">Back to list</a>
    </div>
</div>
<form [formGroup]="editForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="editForm" field="id" rowType="number" i18n-label="@@user.id.label" label="Id" />
    <app-input-row [group]="editForm" field="email" i18n-label="@@user.email.label" label="Email" />
    <app-input-row [group]="editForm" field="password" i18n-label="@@user.password.label" label="Password" />
    <app-input-row [group]="editForm" field="fullname" i18n-label="@@user.fullname.label" label="Fullname" />
    <app-input-row [group]="editForm" field="active" rowType="checkbox" i18n-label="@@user.active.label" label="Active" />
    <app-input-row [group]="editForm" field="socialname" i18n-label="@@user.socialname.label" label="Socialname" />
    <app-input-row [group]="editForm" field="cpf" i18n-label="@@user.cpf.label" label="Cpf" />
    <app-input-row [group]="editForm" field="crm" i18n-label="@@user.crm.label" label="Crm" />
    <app-input-row [group]="editForm" field="countAccess" rowType="number" i18n-label="@@user.countAccess.label" label="Count Access" />
    <app-input-row [group]="editForm" field="role" rowType="select" [options]="roleValues" i18n-label="@@user.role.label" label="Role" />
    <input type="submit" i18n-value="@@user.edit.headline" value="Edit User" class="btn btn-primary mt-4" />
</form>

// src/main/webapp/app/user/user-edit.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate, useParams } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { UserDTO } from 'app/user/user-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    email: yup.string().emptyToNull().max(255).required(),
    password: yup.string().emptyToNull().max(255).required(),
    fullname: yup.string().emptyToNull().max(255).required(),
    active: yup.bool(),
    socialname: yup.string().emptyToNull().max(255),
    cpf: yup.string().emptyToNull().max(255).required(),
    crm: yup.string().emptyToNull().max(255),
    countAccess: yup.number().integer().emptyToNull(),
    role: yup.number().integer().emptyToNull()
  });
}

export default function UserEdit() {
  const { t } = useTranslation();
  useDocumentTitle(t('user.edit.headline'));

  const navigate = useNavigate();
  const [roleValues, setRoleValues] = useState<Map<number,string>>(new Map());
  const params = useParams();
  const currentId = +params.id!;

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const getMessage = (key: string) => {
    const messages: Record<string, string> = {
      USER_EMAIL_UNIQUE: t('exists.user.email'),
      USER_CPF_UNIQUE: t('exists.user.cpf'),
      USER_ROLE_UNIQUE: t('Exists.user.role')
    };
    return messages[key];
  };

  const prepareForm = async () => {
    try {
      const roleValuesResponse = await axios.get('/api/users/roleValues');
      setRoleValues(roleValuesResponse.data);
      const data = (await axios.get('/api/users/' + currentId)).data;
      useFormResult.reset(data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareForm();
  }, []);

  const updateUser = async (data: UserDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.put('/api/users/' + currentId, data);
      navigate('/users', {
            state: {
              msgSuccess: t('user.update.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t, getMessage);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('user.edit.headline')}</h1>
      <div>
        <Link to="/users" className="btn btn-secondary">{t('user.edit.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(updateUser)} noValidate>
      <InputRow useFormResult={useFormResult} object="user" field="id" disabled={true} type="number" />
      <InputRow useFormResult={useFormResult} object="user" field="email" required={true} />
      <InputRow useFormResult={useFormResult} object="user" field="password" required={true} />
      <InputRow useFormResult={useFormResult} object="user" field="fullname" required={true} />
      <InputRow useFormResult={useFormResult} object="user" field="active" type="checkbox" />
      <InputRow useFormResult={useFormResult} object="user" field="socialname" />
      <InputRow useFormResult={useFormResult} object="user" field="cpf" required={true} />
      <InputRow useFormResult={useFormResult} object="user" field="crm" />
      <InputRow useFormResult={useFormResult} object="user" field="countAccess" type="number" />
      <InputRow useFormResult={useFormResult} object="user" field="role" type="select" options={roleValues} />
      <input type="submit" value={t('user.edit.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}
