// src/main/webapp/app/user/user-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { UserService } from 'app/user/user.service';
import { UserDTO } from 'app/user/user.model';


@Component({
  selector: 'app-user-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './user-list.component.html'})
export class UserListComponent implements OnInit, OnDestroy {

  userService = inject(UserService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  users?: UserDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@user.delete.success:User was removed successfully.`,
      'user.phones.user.referenced': $localize`:@@user.phones.user.referenced:This entity is still referenced by Phones ${details?.id} via field User.`,
      'user.address.user.referenced': $localize`:@@user.address.user.referenced:This entity is still referenced by Address ${details?.id} via field User.`,
      'user.doctor.user.referenced': $localize`:@@user.doctor.user.referenced:This entity is still referenced by Doctor ${details?.id} via field User.`,
      'user.patient.user.referenced': $localize`:@@user.patient.user.referenced:This entity is still referenced by Patient ${details?.id} via field User.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.userService.getAllUsers()
        .subscribe({
          next: (data) => this.users = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.userService.deleteUser(id)
        .subscribe({
          next: () => this.router.navigate(['/users'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => {
            if (error.error?.code === 'REFERENCED') {
              const messageParts = error.error.message.split(',');
              this.router.navigate(['/users'], {
                state: {
                  msgError: this.getMessage(messageParts[0], { id: messageParts[1] })
                }
              });
              return;
            }
            this.errorHandler.handleServerError(error.error)
          }
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@user.list.headline">Users</h1>
    <div>
        <a routerLink="/users/add" class="btn btn-primary ms-2" i18n="@@user.list.createNew">Create new User</a>
    </div>
</div>
@if (!users || users.length === 0) {
<div i18n="@@user.list.empty">No Users could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@user.id.label">Id</th>
                <th scope="col" i18n="@@user.email.label">Email</th>
                <th scope="col" i18n="@@user.password.label">Password</th>
                <th scope="col" i18n="@@user.fullname.label">Fullname</th>
                <th scope="col" i18n="@@user.active.label">Active</th>
                <th scope="col" i18n="@@user.socialname.label">Socialname</th>
                <th scope="col" i18n="@@user.cpf.label">Cpf</th>
                <th scope="col" i18n="@@user.crm.label">Crm</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (user of users; track user.id) {
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.fullname }}</td>
                <td>{{ user.active }}</td>
                <td>{{ user.socialname }}</td>
                <td>{{ user.cpf }}</td>
                <td>{{ user.crm }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/users/edit', user.id]" class="btn btn-sm btn-secondary" i18n="@@user.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(user.id!)" class="btn btn-sm btn-secondary" i18n="@@user.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}

// src/main/webapp/app/user/user-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { UserDTO } from 'app/user/user-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function UserList() {
  const { t } = useTranslation();
  useDocumentTitle(t('user.list.headline'));

  const [users, setUsers] = useState<UserDTO[]>([]);
  const navigate = useNavigate();

  const getAllUsers = async () => {
    try {
      const response = await axios.get('/api/users');
      setUsers(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/users/' + id);
      navigate('/users', {
            state: {
              msgInfo: t('user.delete.success')
            }
          });
      getAllUsers();
    } catch (error: any) {
      if (error?.response?.data?.code === 'REFERENCED') {
        const messageParts = error.response.data.message.split(',');
        navigate('/users', {
              state: {
                msgError: t(messageParts[0]!, { id: messageParts[1]! })
              }
            });
        return;
      }
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllUsers();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('user.list.headline')}</h1>
      <div>
        <Link to="/users/add" className="btn btn-primary ms-2">{t('user.list.createNew')}</Link>
      </div>
    </div>
    {!users || users.length === 0 ? (
    <div>{t('user.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('user.id.label')}</th>
            <th scope="col">{t('user.email.label')}</th>
            <th scope="col">{t('user.password.label')}</th>
            <th scope="col">{t('user.fullname.label')}</th>
            <th scope="col">{t('user.active.label')}</th>
            <th scope="col">{t('user.socialname.label')}</th>
            <th scope="col">{t('user.cpf.label')}</th>
            <th scope="col">{t('user.crm.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {users.map((user) => (
          <tr key={user.id}>
            <td>{user.id}</td>
            <td>{user.email}</td>
            <td>{user.password}</td>
            <td>{user.fullname}</td>
            <td>{user.active?.toString()}</td>
            <td>{user.socialname}</td>
            <td>{user.cpf}</td>
            <td>{user.crm}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/users/edit/' + user.id} className="btn btn-sm btn-secondary">{t('user.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(user.id!)} className="btn btn-sm btn-secondary">{t('user.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}
