// src/main/webapp/app/password-token/password-token-edit.tsx
import React, { useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate, useParams } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { PasswordTokenDTO } from 'app/password-token/password-token-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    token: yup.string().emptyToNull().uuid(),
    expirationTime: yup.string().emptyToNull(),
    typeToken: yup.string().emptyToNull().max(255),
    used: yup.bool()
  });
}

export default function PasswordTokenEdit() {
  const { t } = useTranslation();
  useDocumentTitle(t('passwordToken.edit.headline'));

  const navigate = useNavigate();
  const params = useParams();
  const currentId = +params.id!;

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareForm = async () => {
    try {
      const data = (await axios.get('/api/passwordTokens/' + currentId)).data;
      useFormResult.reset(data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareForm();
  }, []);

  const updatePasswordToken = async (data: PasswordTokenDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.put('/api/passwordTokens/' + currentId, data);
      navigate('/passwordTokens', {
            state: {
              msgSuccess: t('passwordToken.update.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('passwordToken.edit.headline')}</h1>
      <div>
        <Link to="/passwordTokens" className="btn btn-secondary">{t('passwordToken.edit.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(updatePasswordToken)} noValidate>
      <InputRow useFormResult={useFormResult} object="passwordToken" field="id" disabled={true} type="number" />
      <InputRow useFormResult={useFormResult} object="passwordToken" field="token" />
      <InputRow useFormResult={useFormResult} object="passwordToken" field="expirationTime" type="datetimepicker" />
      <InputRow useFormResult={useFormResult} object="passwordToken" field="typeToken" />
      <InputRow useFormResult={useFormResult} object="passwordToken" field="used" type="checkbox" />
      <input type="submit" value={t('passwordToken.edit.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/password-token/password-token-edit.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { PasswordTokenService } from 'app/password-token/password-token.service';
import { PasswordTokenDTO } from 'app/password-token/password-token.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { updateForm, validUuid } from 'app/common/utils';


@Component({
  selector: 'app-password-token-edit',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './password-token-edit.component.html'
})
export class PasswordTokenEditComponent implements OnInit {

  passwordTokenService = inject(PasswordTokenService);
  route = inject(ActivatedRoute);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  currentId?: number;

  editForm = new FormGroup({
    id: new FormControl({ value: null, disabled: true }),
    token: new FormControl(null, [validUuid]),
    expirationTime: new FormControl(null),
    typeToken: new FormControl(null, [Validators.maxLength(255)]),
    used: new FormControl(false)
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      updated: $localize`:@@passwordToken.update.success:Password Token was updated successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.currentId = +this.route.snapshot.params['id'];
    this.passwordTokenService.getPasswordToken(this.currentId!)
        .subscribe({
          next: (data) => updateForm(this.editForm, data),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.editForm.markAllAsTouched();
    if (!this.editForm.valid) {
      return;
    }
    const data = new PasswordTokenDTO(this.editForm.value);
    this.passwordTokenService.updatePasswordToken(this.currentId!, data)
        .subscribe({
          next: () => this.router.navigate(['/passwordTokens'], {
            state: {
              msgSuccess: this.getMessage('updated')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.editForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@passwordToken.edit.headline">Edit Password Token</h1>
    <div>
        <a routerLink="/passwordTokens" class="btn btn-secondary" i18n="@@passwordToken.edit.back">Back to list</a>
    </div>
</div>
<form [formGroup]="editForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="editForm" field="id" rowType="number" i18n-label="@@passwordToken.id.label" label="Id" />
    <app-input-row [group]="editForm" field="token" i18n-label="@@passwordToken.token.label" label="Token" />
    <app-input-row [group]="editForm" field="expirationTime" rowType="datetimepicker" i18n-label="@@passwordToken.expirationTime.label" label="Expiration Time" />
    <app-input-row [group]="editForm" field="typeToken" i18n-label="@@passwordToken.typeToken.label" label="Type Token" />
    <app-input-row [group]="editForm" field="used" rowType="checkbox" i18n-label="@@passwordToken.used.label" label="Used" />
    <input type="submit" i18n-value="@@passwordToken.edit.headline" value="Edit Password Token" class="btn btn-primary mt-4" />
</form>
