// src/main/webapp/app/password-token/password-token-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { PasswordTokenDTO } from 'app/password-token/password-token-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function PasswordTokenList() {
  const { t } = useTranslation();
  useDocumentTitle(t('passwordToken.list.headline'));

  const [passwordTokens, setPasswordTokens] = useState<PasswordTokenDTO[]>([]);
  const navigate = useNavigate();

  const getAllPasswordTokens = async () => {
    try {
      const response = await axios.get('/api/passwordTokens');
      setPasswordTokens(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/passwordTokens/' + id);
      navigate('/passwordTokens', {
            state: {
              msgInfo: t('passwordToken.delete.success')
            }
          });
      getAllPasswordTokens();
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllPasswordTokens();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('passwordToken.list.headline')}</h1>
      <div>
        <Link to="/passwordTokens/add" className="btn btn-primary ms-2">{t('passwordToken.list.createNew')}</Link>
      </div>
    </div>
    {!passwordTokens || passwordTokens.length === 0 ? (
    <div>{t('passwordToken.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('passwordToken.id.label')}</th>
            <th scope="col">{t('passwordToken.token.label')}</th>
            <th scope="col">{t('passwordToken.expirationTime.label')}</th>
            <th scope="col">{t('passwordToken.typeToken.label')}</th>
            <th scope="col">{t('passwordToken.used.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {passwordTokens.map((passwordToken) => (
          <tr key={passwordToken.id}>
            <td>{passwordToken.id}</td>
            <td>{passwordToken.token}</td>
            <td>{passwordToken.expirationTime}</td>
            <td>{passwordToken.typeToken}</td>
            <td>{passwordToken.used?.toString()}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/passwordTokens/edit/' + passwordToken.id} className="btn btn-sm btn-secondary">{t('passwordToken.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(passwordToken.id!)} className="btn btn-sm btn-secondary">{t('passwordToken.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}

// src/main/webapp/app/password-token/password-token-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { PasswordTokenService } from 'app/password-token/password-token.service';
import { PasswordTokenDTO } from 'app/password-token/password-token.model';


@Component({
  selector: 'app-password-token-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './password-token-list.component.html'})
export class PasswordTokenListComponent implements OnInit, OnDestroy {

  passwordTokenService = inject(PasswordTokenService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  passwordTokens?: PasswordTokenDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@passwordToken.delete.success:Password Token was removed successfully.`    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.passwordTokenService.getAllPasswordTokens()
        .subscribe({
          next: (data) => this.passwordTokens = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.passwordTokenService.deletePasswordToken(id)
        .subscribe({
          next: () => this.router.navigate(['/passwordTokens'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@passwordToken.list.headline">Password Tokens</h1>
    <div>
        <a routerLink="/passwordTokens/add" class="btn btn-primary ms-2" i18n="@@passwordToken.list.createNew">Create new Password Token</a>
    </div>
</div>
@if (!passwordTokens || passwordTokens.length === 0) {
<div i18n="@@passwordToken.list.empty">No Password Tokens could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@passwordToken.id.label">Id</th>
                <th scope="col" i18n="@@passwordToken.token.label">Token</th>
                <th scope="col" i18n="@@passwordToken.expirationTime.label">Expiration Time</th>
                <th scope="col" i18n="@@passwordToken.typeToken.label">Type Token</th>
                <th scope="col" i18n="@@passwordToken.used.label">Used</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (passwordToken of passwordTokens; track passwordToken.id) {
            <tr>
                <td>{{ passwordToken.id }}</td>
                <td>{{ passwordToken.token }}</td>
                <td>{{ passwordToken.expirationTime }}</td>
                <td>{{ passwordToken.typeToken }}</td>
                <td>{{ passwordToken.used }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/passwordTokens/edit', passwordToken.id]" class="btn btn-sm btn-secondary" i18n="@@passwordToken.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(passwordToken.id!)" class="btn btn-sm btn-secondary" i18n="@@passwordToken.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}
