// src/main/webapp/app/password-token/password-token-add.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { PasswordTokenDTO } from 'app/password-token/password-token-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    token: yup.string().emptyToNull().uuid(),
    expirationTime: yup.string().emptyToNull(),
    typeToken: yup.string().emptyToNull().max(255),
    used: yup.bool()
  });
}

export default function PasswordTokenAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('passwordToken.add.headline'));

  const navigate = useNavigate();

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const createPasswordToken = async (data: PasswordTokenDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/passwordTokens', data);
      navigate('/passwordTokens', {
            state: {
              msgSuccess: t('passwordToken.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('passwordToken.add.headline')}</h1>
      <div>
        <Link to="/passwordTokens" className="btn btn-secondary">{t('passwordToken.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createPasswordToken)} noValidate>
      <InputRow useFormResult={useFormResult} object="passwordToken" field="token" />
      <InputRow useFormResult={useFormResult} object="passwordToken" field="expirationTime" type="datetimepicker" />
      <InputRow useFormResult={useFormResult} object="passwordToken" field="typeToken" />
      <InputRow useFormResult={useFormResult} object="passwordToken" field="used" type="checkbox" />
      <input type="submit" value={t('passwordToken.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/password-token/password-token-add.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { PasswordTokenService } from 'app/password-token/password-token.service';
import { PasswordTokenDTO } from 'app/password-token/password-token.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { validUuid } from 'app/common/utils';


@Component({
  selector: 'app-password-token-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './password-token-add.component.html'
})
export class PasswordTokenAddComponent {

  passwordTokenService = inject(PasswordTokenService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  addForm = new FormGroup({
    token: new FormControl(null, [validUuid]),
    expirationTime: new FormControl(null),
    typeToken: new FormControl(null, [Validators.maxLength(255)]),
    used: new FormControl(false)
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@passwordToken.create.success:Password Token was created successfully.`
    };
    return messages[key];
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new PasswordTokenDTO(this.addForm.value);
    this.passwordTokenService.createPasswordToken(data)
        .subscribe({
          next: () => this.router.navigate(['/passwordTokens'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@passwordToken.add.headline">Add Password Token</h1>
    <div>
        <a routerLink="/passwordTokens" class="btn btn-secondary" i18n="@@passwordToken.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="token" i18n-label="@@passwordToken.token.label" label="Token" />
    <app-input-row [group]="addForm" field="expirationTime" rowType="datetimepicker" i18n-label="@@passwordToken.expirationTime.label" label="Expiration Time" />
    <app-input-row [group]="addForm" field="typeToken" i18n-label="@@passwordToken.typeToken.label" label="Type Token" />
    <app-input-row [group]="addForm" field="used" rowType="checkbox" i18n-label="@@passwordToken.used.label" label="Used" />
    <input type="submit" i18n-value="@@passwordToken.add.headline" value="Add Password Token" class="btn btn-primary mt-4" />
</form>
