// src/main/webapp/app/newsletter/newsletter-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { NewsletterService } from 'app/newsletter/newsletter.service';
import { NewsletterDTO } from 'app/newsletter/newsletter.model';


@Component({
  selector: 'app-newsletter-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './newsletter-list.component.html'})
export class NewsletterListComponent implements OnInit, OnDestroy {

  newsletterService = inject(NewsletterService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  newsletters?: NewsletterDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@newsletter.delete.success:Newsletter was removed successfully.`,
      'newsletter.emails.newsletter.referenced': $localize`:@@newsletter.emails.newsletter.referenced:This entity is still referenced by Emails ${details?.id} via field Newsletter.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.newsletterService.getAllNewsletters()
        .subscribe({
          next: (data) => this.newsletters = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.newsletterService.deleteNewsletter(id)
        .subscribe({
          next: () => this.router.navigate(['/newsletters'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => {
            if (error.error?.code === 'REFERENCED') {
              const messageParts = error.error.message.split(',');
              this.router.navigate(['/newsletters'], {
                state: {
                  msgError: this.getMessage(messageParts[0], { id: messageParts[1] })
                }
              });
              return;
            }
            this.errorHandler.handleServerError(error.error)
          }
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@newsletter.list.headline">Newsletters</h1>
    <div>
        <a routerLink="/newsletters/add" class="btn btn-primary ms-2" i18n="@@newsletter.list.createNew">Create new Newsletter</a>
    </div>
</div>
@if (!newsletters || newsletters.length === 0) {
<div i18n="@@newsletter.list.empty">No Newsletters could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@newsletter.id.label">Id</th>
                <th scope="col" i18n="@@newsletter.title.label">Title</th>
                <th scope="col" i18n="@@newsletter.deliveryDate.label">Delivery Date</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (newsletter of newsletters; track newsletter.id) {
            <tr>
                <td>{{ newsletter.id }}</td>
                <td>{{ newsletter.title }}</td>
                <td>{{ newsletter.deliveryDate }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/newsletters/edit', newsletter.id]" class="btn btn-sm btn-secondary" i18n="@@newsletter.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(newsletter.id!)" class="btn btn-sm btn-secondary" i18n="@@newsletter.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}

// src/main/webapp/app/newsletter/newsletter-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { NewsletterDTO } from 'app/newsletter/newsletter-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function NewsletterList() {
  const { t } = useTranslation();
  useDocumentTitle(t('newsletter.list.headline'));

  const [newsletters, setNewsletters] = useState<NewsletterDTO[]>([]);
  const navigate = useNavigate();

  const getAllNewsletters = async () => {
    try {
      const response = await axios.get('/api/newsletters');
      setNewsletters(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/newsletters/' + id);
      navigate('/newsletters', {
            state: {
              msgInfo: t('newsletter.delete.success')
            }
          });
      getAllNewsletters();
    } catch (error: any) {
      if (error?.response?.data?.code === 'REFERENCED') {
        const messageParts = error.response.data.message.split(',');
        navigate('/newsletters', {
              state: {
                msgError: t(messageParts[0]!, { id: messageParts[1]! })
              }
            });
        return;
      }
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllNewsletters();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('newsletter.list.headline')}</h1>
      <div>
        <Link to="/newsletters/add" className="btn btn-primary ms-2">{t('newsletter.list.createNew')}</Link>
      </div>
    </div>
    {!newsletters || newsletters.length === 0 ? (
    <div>{t('newsletter.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('newsletter.id.label')}</th>
            <th scope="col">{t('newsletter.title.label')}</th>
            <th scope="col">{t('newsletter.deliveryDate.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {newsletters.map((newsletter) => (
          <tr key={newsletter.id}>
            <td>{newsletter.id}</td>
            <td>{newsletter.title}</td>
            <td>{newsletter.deliveryDate}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/newsletters/edit/' + newsletter.id} className="btn btn-sm btn-secondary">{t('newsletter.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(newsletter.id!)} className="btn btn-sm btn-secondary">{t('newsletter.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}
