// src/main/webapp/app/newsletter/newsletter-add.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { NewsletterDTO } from 'app/newsletter/newsletter-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    title: yup.string().emptyToNull().max(255),
    content: yup.string().emptyToNull(),
    file: yup.object().emptyToNull().json(),
    deliveryDate: yup.string().emptyToNull().required()
  });
}

export default function NewsletterAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('newsletter.add.headline'));

  const navigate = useNavigate();

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const createNewsletter = async (data: NewsletterDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/newsletters', data);
      navigate('/newsletters', {
            state: {
              msgSuccess: t('newsletter.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('newsletter.add.headline')}</h1>
      <div>
        <Link to="/newsletters" className="btn btn-secondary">{t('newsletter.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createNewsletter)} noValidate>
      <InputRow useFormResult={useFormResult} object="newsletter" field="title" />
      <InputRow useFormResult={useFormResult} object="newsletter" field="content" type="textarea" />
      <InputRow useFormResult={useFormResult} object="newsletter" field="file" type="file" />
      <InputRow useFormResult={useFormResult} object="newsletter" field="deliveryDate" required={true} type="datetimepicker" />
      <input type="submit" value={t('newsletter.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/newsletter/newsletter-add.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { NewsletterService } from 'app/newsletter/newsletter.service';
import { NewsletterDTO } from 'app/newsletter/newsletter.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';


@Component({
  selector: 'app-newsletter-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './newsletter-add.component.html'
})
export class NewsletterAddComponent {

  newsletterService = inject(NewsletterService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  addForm = new FormGroup({
    title: new FormControl(null, [Validators.maxLength(255)]),
    content: new FormControl(null),
    file: new FormControl(null),
    deliveryDate: new FormControl(null, [Validators.required])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@newsletter.create.success:Newsletter was created successfully.`
    };
    return messages[key];
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new NewsletterDTO(this.addForm.value);
    this.newsletterService.createNewsletter(data)
        .subscribe({
          next: () => this.router.navigate(['/newsletters'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@newsletter.add.headline">Add Newsletter</h1>
    <div>
        <a routerLink="/newsletters" class="btn btn-secondary" i18n="@@newsletter.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="title" i18n-label="@@newsletter.title.label" label="Title" />
    <app-input-row [group]="addForm" field="content" rowType="textarea" i18n-label="@@newsletter.content.label" label="Content" />
    <app-input-row [group]="addForm" field="file" rowType="file" i18n-label="@@newsletter.file.label" label="File" />
    <app-input-row [group]="addForm" field="deliveryDate" rowType="datetimepicker" i18n-label="@@newsletter.deliveryDate.label" label="Delivery Date" />
    <input type="submit" i18n-value="@@newsletter.add.headline" value="Add Newsletter" class="btn btn-primary mt-4" />
</form>
