// src/main/webapp/app/newsletter/newsletter-edit.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { NewsletterService } from 'app/newsletter/newsletter.service';
import { NewsletterDTO } from 'app/newsletter/newsletter.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { updateForm } from 'app/common/utils';


@Component({
  selector: 'app-newsletter-edit',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './newsletter-edit.component.html'
})
export class NewsletterEditComponent implements OnInit {

  newsletterService = inject(NewsletterService);
  route = inject(ActivatedRoute);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  currentId?: number;

  editForm = new FormGroup({
    id: new FormControl({ value: null, disabled: true }),
    title: new FormControl(null, [Validators.maxLength(255)]),
    content: new FormControl(null),
    file: new FormControl(null),
    deliveryDate: new FormControl(null, [Validators.required])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      updated: $localize`:@@newsletter.update.success:Newsletter was updated successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.currentId = +this.route.snapshot.params['id'];
    this.newsletterService.getNewsletter(this.currentId!)
        .subscribe({
          next: (data) => updateForm(this.editForm, data),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.editForm.markAllAsTouched();
    if (!this.editForm.valid) {
      return;
    }
    const data = new NewsletterDTO(this.editForm.value);
    this.newsletterService.updateNewsletter(this.currentId!, data)
        .subscribe({
          next: () => this.router.navigate(['/newsletters'], {
            state: {
              msgSuccess: this.getMessage('updated')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.editForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@newsletter.edit.headline">Edit Newsletter</h1>
    <div>
        <a routerLink="/newsletters" class="btn btn-secondary" i18n="@@newsletter.edit.back">Back to list</a>
    </div>
</div>
<form [formGroup]="editForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="editForm" field="id" rowType="number" i18n-label="@@newsletter.id.label" label="Id" />
    <app-input-row [group]="editForm" field="title" i18n-label="@@newsletter.title.label" label="Title" />
    <app-input-row [group]="editForm" field="content" rowType="textarea" i18n-label="@@newsletter.content.label" label="Content" />
    <app-input-row [group]="editForm" field="file" rowType="file" [downloadLink]="'/api/phoness/' + currentId + '/file'" i18n-label="@@newsletter.file.label" label="File" />
    <app-input-row [group]="editForm" field="deliveryDate" rowType="datetimepicker" i18n-label="@@newsletter.deliveryDate.label" label="Delivery Date" />
    <input type="submit" i18n-value="@@newsletter.edit.headline" value="Edit Newsletter" class="btn btn-primary mt-4" />
</form>

// src/main/webapp/app/newsletter/newsletter-edit.tsx
import React, { useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate, useParams } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { NewsletterDTO } from 'app/newsletter/newsletter-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    title: yup.string().emptyToNull().max(255),
    content: yup.string().emptyToNull(),
    file: yup.object().emptyToNull().json(),
    deliveryDate: yup.string().emptyToNull().required()
  });
}

export default function NewsletterEdit() {
  const { t } = useTranslation();
  useDocumentTitle(t('newsletter.edit.headline'));

  const navigate = useNavigate();
  const params = useParams();
  const currentId = +params.id!;

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareForm = async () => {
    try {
      const data = (await axios.get('/api/newsletters/' + currentId)).data;
      if (data.file) {
        data.file = JSON.stringify(data.file, undefined, 2);
      }
      useFormResult.reset(data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareForm();
  }, []);

  const updateNewsletter = async (data: NewsletterDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.put('/api/newsletters/' + currentId, data);
      navigate('/newsletters', {
            state: {
              msgSuccess: t('newsletter.update.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('newsletter.edit.headline')}</h1>
      <div>
        <Link to="/newsletters" className="btn btn-secondary">{t('newsletter.edit.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(updateNewsletter)} noValidate>
      <InputRow useFormResult={useFormResult} object="newsletter" field="id" disabled={true} type="number" />
      <InputRow useFormResult={useFormResult} object="newsletter" field="title" />
      <InputRow useFormResult={useFormResult} object="newsletter" field="content" type="textarea" />
      <InputRow useFormResult={useFormResult} object="newsletter" field="file" type="file" downloadLink={'/api/phoness/' + currentId + '/file'} />
      <InputRow useFormResult={useFormResult} object="newsletter" field="deliveryDate" required={true} type="datetimepicker" />
      <input type="submit" value={t('newsletter.edit.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}
