// src/main/webapp/app/schedule/schedule-add.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { ScheduleDTO } from 'app/schedule/schedule-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    appoimentTime: yup.string().emptyToNull(),
    videoHashLink: yup.string().emptyToNull().uuid(),
    note: yup.string().emptyToNull(),
    patient: yup.number().integer().emptyToNull(),
    doctorsAvailableSchedule: yup.number().integer().emptyToNull()
  });
}

export default function ScheduleAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('schedule.add.headline'));

  const navigate = useNavigate();
  const [patientValues, setPatientValues] = useState<Map<number,string>>(new Map());
  const [doctorsAvailableScheduleValues, setDoctorsAvailableScheduleValues] = useState<Map<number,string>>(new Map());

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareRelations = async () => {
    try {
      const patientValuesResponse = await axios.get('/api/schedules/patientValues');
      setPatientValues(patientValuesResponse.data);
      const doctorsAvailableScheduleValuesResponse = await axios.get('/api/schedules/doctorsAvailableScheduleValues');
      setDoctorsAvailableScheduleValues(doctorsAvailableScheduleValuesResponse.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareRelations();
  }, []);

  const createSchedule = async (data: ScheduleDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/schedules', data);
      navigate('/schedules', {
            state: {
              msgSuccess: t('schedule.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('schedule.add.headline')}</h1>
      <div>
        <Link to="/schedules" className="btn btn-secondary">{t('schedule.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createSchedule)} noValidate>
      <InputRow useFormResult={useFormResult} object="schedule" field="appoimentTime" type="datetimepicker" />
      <InputRow useFormResult={useFormResult} object="schedule" field="videoHashLink" />
      <InputRow useFormResult={useFormResult} object="schedule" field="note" type="textarea" />
      <InputRow useFormResult={useFormResult} object="schedule" field="patient" type="select" options={patientValues} />
      <InputRow useFormResult={useFormResult} object="schedule" field="doctorsAvailableSchedule" type="select" options={doctorsAvailableScheduleValues} />
      <input type="submit" value={t('schedule.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/schedule/schedule-add.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { ScheduleService } from 'app/schedule/schedule.service';
import { ScheduleDTO } from 'app/schedule/schedule.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { validUuid } from 'app/common/utils';


@Component({
  selector: 'app-schedule-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './schedule-add.component.html'
})
export class ScheduleAddComponent implements OnInit {

  scheduleService = inject(ScheduleService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  patientValues?: Map<number,string>;
  doctorsAvailableScheduleValues?: Map<number,string>;

  addForm = new FormGroup({
    appoimentTime: new FormControl(null),
    videoHashLink: new FormControl(null, [validUuid]),
    note: new FormControl(null),
    patient: new FormControl(null),
    doctorsAvailableSchedule: new FormControl(null)
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@schedule.create.success:Schedule was created successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.scheduleService.getPatientValues()
        .subscribe({
          next: (data) => this.patientValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.scheduleService.getDoctorsAvailableScheduleValues()
        .subscribe({
          next: (data) => this.doctorsAvailableScheduleValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new ScheduleDTO(this.addForm.value);
    this.scheduleService.createSchedule(data)
        .subscribe({
          next: () => this.router.navigate(['/schedules'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@schedule.add.headline">Add Schedule</h1>
    <div>
        <a routerLink="/schedules" class="btn btn-secondary" i18n="@@schedule.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="appoimentTime" rowType="datetimepicker" i18n-label="@@schedule.appoimentTime.label" label="Appoiment Time" />
    <app-input-row [group]="addForm" field="videoHashLink" i18n-label="@@schedule.videoHashLink.label" label="Video Hash Link" />
    <app-input-row [group]="addForm" field="note" rowType="textarea" i18n-label="@@schedule.note.label" label="Note" />
    <app-input-row [group]="addForm" field="patient" rowType="select" [options]="patientValues" i18n-label="@@schedule.patient.label" label="Patient" />
    <app-input-row [group]="addForm" field="doctorsAvailableSchedule" rowType="select" [options]="doctorsAvailableScheduleValues" i18n-label="@@schedule.doctorsAvailableSchedule.label" label="Doctors Available Schedule" />
    <input type="submit" i18n-value="@@schedule.add.headline" value="Add Schedule" class="btn btn-primary mt-4" />
</form>
