// src/main/webapp/app/schedule/schedule-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { ScheduleDTO } from 'app/schedule/schedule-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function ScheduleList() {
  const { t } = useTranslation();
  useDocumentTitle(t('schedule.list.headline'));

  const [schedules, setSchedules] = useState<ScheduleDTO[]>([]);
  const navigate = useNavigate();

  const getAllSchedules = async () => {
    try {
      const response = await axios.get('/api/schedules');
      setSchedules(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/schedules/' + id);
      navigate('/schedules', {
            state: {
              msgInfo: t('schedule.delete.success')
            }
          });
      getAllSchedules();
    } catch (error: any) {
      if (error?.response?.data?.code === 'REFERENCED') {
        const messageParts = error.response.data.message.split(',');
        navigate('/schedules', {
              state: {
                msgError: t(messageParts[0]!, { id: messageParts[1]! })
              }
            });
        return;
      }
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllSchedules();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('schedule.list.headline')}</h1>
      <div>
        <Link to="/schedules/add" className="btn btn-primary ms-2">{t('schedule.list.createNew')}</Link>
      </div>
    </div>
    {!schedules || schedules.length === 0 ? (
    <div>{t('schedule.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('schedule.id.label')}</th>
            <th scope="col">{t('schedule.appoimentTime.label')}</th>
            <th scope="col">{t('schedule.videoHashLink.label')}</th>
            <th scope="col">{t('schedule.patient.label')}</th>
            <th scope="col">{t('schedule.doctorsAvailableSchedule.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {schedules.map((schedule) => (
          <tr key={schedule.id}>
            <td>{schedule.id}</td>
            <td>{schedule.appoimentTime}</td>
            <td>{schedule.videoHashLink}</td>
            <td>{schedule.patient}</td>
            <td>{schedule.doctorsAvailableSchedule}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/schedules/edit/' + schedule.id} className="btn btn-sm btn-secondary">{t('schedule.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(schedule.id!)} className="btn btn-sm btn-secondary">{t('schedule.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}

// src/main/webapp/app/schedule/schedule-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { ScheduleService } from 'app/schedule/schedule.service';
import { ScheduleDTO } from 'app/schedule/schedule.model';


@Component({
  selector: 'app-schedule-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './schedule-list.component.html'})
export class ScheduleListComponent implements OnInit, OnDestroy {

  scheduleService = inject(ScheduleService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  schedules?: ScheduleDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@schedule.delete.success:Schedule was removed successfully.`,
      'schedule.medicalRecord.schedule.referenced': $localize`:@@schedule.medicalRecord.schedule.referenced:This entity is still referenced by Medical Record ${details?.id} via field Schedule.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.scheduleService.getAllSchedules()
        .subscribe({
          next: (data) => this.schedules = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.scheduleService.deleteSchedule(id)
        .subscribe({
          next: () => this.router.navigate(['/schedules'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => {
            if (error.error?.code === 'REFERENCED') {
              const messageParts = error.error.message.split(',');
              this.router.navigate(['/schedules'], {
                state: {
                  msgError: this.getMessage(messageParts[0], { id: messageParts[1] })
                }
              });
              return;
            }
            this.errorHandler.handleServerError(error.error)
          }
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@schedule.list.headline">Schedules</h1>
    <div>
        <a routerLink="/schedules/add" class="btn btn-primary ms-2" i18n="@@schedule.list.createNew">Create new Schedule</a>
    </div>
</div>
@if (!schedules || schedules.length === 0) {
<div i18n="@@schedule.list.empty">No Schedules could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@schedule.id.label">Id</th>
                <th scope="col" i18n="@@schedule.appoimentTime.label">Appoiment Time</th>
                <th scope="col" i18n="@@schedule.videoHashLink.label">Video Hash Link</th>
                <th scope="col" i18n="@@schedule.patient.label">Patient</th>
                <th scope="col" i18n="@@schedule.doctorsAvailableSchedule.label">Doctors Available Schedule</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (schedule of schedules; track schedule.id) {
            <tr>
                <td>{{ schedule.id }}</td>
                <td>{{ schedule.appoimentTime }}</td>
                <td>{{ schedule.videoHashLink }}</td>
                <td>{{ schedule.patient }}</td>
                <td>{{ schedule.doctorsAvailableSchedule }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/schedules/edit', schedule.id]" class="btn btn-sm btn-secondary" i18n="@@schedule.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(schedule.id!)" class="btn btn-sm btn-secondary" i18n="@@schedule.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}
