// src/main/webapp/app/responsible/responsible-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { ResponsibleDTO } from 'app/responsible/responsible-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function ResponsibleList() {
  const { t } = useTranslation();
  useDocumentTitle(t('responsible.list.headline'));

  const [responsibles, setResponsibles] = useState<ResponsibleDTO[]>([]);
  const navigate = useNavigate();

  const getAllResponsibles = async () => {
    try {
      const response = await axios.get('/api/responsibles');
      setResponsibles(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/responsibles/' + id);
      navigate('/responsibles', {
            state: {
              msgInfo: t('responsible.delete.success')
            }
          });
      getAllResponsibles();
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllResponsibles();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('responsible.list.headline')}</h1>
      <div>
        <Link to="/responsibles/add" className="btn btn-primary ms-2">{t('responsible.list.createNew')}</Link>
      </div>
    </div>
    {!responsibles || responsibles.length === 0 ? (
    <div>{t('responsible.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('responsible.id.label')}</th>
            <th scope="col">{t('responsible.name.label')}</th>
            <th scope="col">{t('responsible.degreeOfRelatedness.label')}</th>
            <th scope="col">{t('responsible.phones.label')}</th>
            <th scope="col">{t('responsible.patient.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {responsibles.map((responsible) => (
          <tr key={responsible.id}>
            <td>{responsible.id}</td>
            <td>{responsible.name}</td>
            <td>{responsible.degreeOfRelatedness}</td>
            <td>{responsible.phones}</td>
            <td>{responsible.patient}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/responsibles/edit/' + responsible.id} className="btn btn-sm btn-secondary">{t('responsible.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(responsible.id!)} className="btn btn-sm btn-secondary">{t('responsible.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}

// src/main/webapp/app/responsible/responsible-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { ResponsibleService } from 'app/responsible/responsible.service';
import { ResponsibleDTO } from 'app/responsible/responsible.model';


@Component({
  selector: 'app-responsible-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './responsible-list.component.html'})
export class ResponsibleListComponent implements OnInit, OnDestroy {

  responsibleService = inject(ResponsibleService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  responsibles?: ResponsibleDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@responsible.delete.success:Responsible was removed successfully.`    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.responsibleService.getAllResponsibles()
        .subscribe({
          next: (data) => this.responsibles = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.responsibleService.deleteResponsible(id)
        .subscribe({
          next: () => this.router.navigate(['/responsibles'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@responsible.list.headline">Responsibles</h1>
    <div>
        <a routerLink="/responsibles/add" class="btn btn-primary ms-2" i18n="@@responsible.list.createNew">Create new Responsible</a>
    </div>
</div>
@if (!responsibles || responsibles.length === 0) {
<div i18n="@@responsible.list.empty">No Responsibles could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@responsible.id.label">Id</th>
                <th scope="col" i18n="@@responsible.name.label">Name</th>
                <th scope="col" i18n="@@responsible.degreeOfRelatedness.label">Degree Of Relatedness</th>
                <th scope="col" i18n="@@responsible.phones.label">Phones</th>
                <th scope="col" i18n="@@responsible.patient.label">Patient</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (responsible of responsibles; track responsible.id) {
            <tr>
                <td>{{ responsible.id }}</td>
                <td>{{ responsible.name }}</td>
                <td>{{ responsible.degreeOfRelatedness }}</td>
                <td>{{ responsible.phones }}</td>
                <td>{{ responsible.patient }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/responsibles/edit', responsible.id]" class="btn btn-sm btn-secondary" i18n="@@responsible.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(responsible.id!)" class="btn btn-sm btn-secondary" i18n="@@responsible.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}
