// src/main/webapp/app/responsible/responsible-add.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { ResponsibleService } from 'app/responsible/responsible.service';
import { ResponsibleDTO } from 'app/responsible/responsible.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';


@Component({
  selector: 'app-responsible-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './responsible-add.component.html'
})
export class ResponsibleAddComponent implements OnInit {

  responsibleService = inject(ResponsibleService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  phonesValues?: Map<number,string>;
  patientValues?: Map<number,string>;

  addForm = new FormGroup({
    name: new FormControl(null, [Validators.maxLength(255)]),
    degreeOfRelatedness: new FormControl(null, [Validators.maxLength(255)]),
    phones: new FormControl(null, [Validators.required]),
    patient: new FormControl(null, [Validators.required])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@responsible.create.success:Responsible was created successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.responsibleService.getPhonesValues()
        .subscribe({
          next: (data) => this.phonesValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.responsibleService.getPatientValues()
        .subscribe({
          next: (data) => this.patientValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new ResponsibleDTO(this.addForm.value);
    this.responsibleService.createResponsible(data)
        .subscribe({
          next: () => this.router.navigate(['/responsibles'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@responsible.add.headline">Add Responsible</h1>
    <div>
        <a routerLink="/responsibles" class="btn btn-secondary" i18n="@@responsible.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="name" i18n-label="@@responsible.name.label" label="Name" />
    <app-input-row [group]="addForm" field="degreeOfRelatedness" i18n-label="@@responsible.degreeOfRelatedness.label" label="Degree Of Relatedness" />
    <app-input-row [group]="addForm" field="phones" rowType="select" [options]="phonesValues" i18n-label="@@responsible.phones.label" label="Phones" />
    <app-input-row [group]="addForm" field="patient" rowType="select" [options]="patientValues" i18n-label="@@responsible.patient.label" label="Patient" />
    <input type="submit" i18n-value="@@responsible.add.headline" value="Add Responsible" class="btn btn-primary mt-4" />
</form>

// src/main/webapp/app/responsible/responsible-add.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { ResponsibleDTO } from 'app/responsible/responsible-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    name: yup.string().emptyToNull().max(255),
    degreeOfRelatedness: yup.string().emptyToNull().max(255),
    phones: yup.number().integer().emptyToNull().required(),
    patient: yup.number().integer().emptyToNull().required()
  });
}

export default function ResponsibleAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('responsible.add.headline'));

  const navigate = useNavigate();
  const [phonesValues, setPhonesValues] = useState<Map<number,string>>(new Map());
  const [patientValues, setPatientValues] = useState<Map<number,string>>(new Map());

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareRelations = async () => {
    try {
      const phonesValuesResponse = await axios.get('/api/responsibles/phonesValues');
      setPhonesValues(phonesValuesResponse.data);
      const patientValuesResponse = await axios.get('/api/responsibles/patientValues');
      setPatientValues(patientValuesResponse.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareRelations();
  }, []);

  const createResponsible = async (data: ResponsibleDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/responsibles', data);
      navigate('/responsibles', {
            state: {
              msgSuccess: t('responsible.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('responsible.add.headline')}</h1>
      <div>
        <Link to="/responsibles" className="btn btn-secondary">{t('responsible.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createResponsible)} noValidate>
      <InputRow useFormResult={useFormResult} object="responsible" field="name" />
      <InputRow useFormResult={useFormResult} object="responsible" field="degreeOfRelatedness" />
      <InputRow useFormResult={useFormResult} object="responsible" field="phones" required={true} type="select" options={phonesValues} />
      <InputRow useFormResult={useFormResult} object="responsible" field="patient" required={true} type="select" options={patientValues} />
      <input type="submit" value={t('responsible.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}
