// src/main/webapp/app/responsible/responsible-edit.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate, useParams } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { ResponsibleDTO } from 'app/responsible/responsible-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    name: yup.string().emptyToNull().max(255),
    degreeOfRelatedness: yup.string().emptyToNull().max(255),
    phones: yup.number().integer().emptyToNull().required(),
    patient: yup.number().integer().emptyToNull().required()
  });
}

export default function ResponsibleEdit() {
  const { t } = useTranslation();
  useDocumentTitle(t('responsible.edit.headline'));

  const navigate = useNavigate();
  const [phonesValues, setPhonesValues] = useState<Map<number,string>>(new Map());
  const [patientValues, setPatientValues] = useState<Map<number,string>>(new Map());
  const params = useParams();
  const currentId = +params.id!;

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareForm = async () => {
    try {
      const phonesValuesResponse = await axios.get('/api/responsibles/phonesValues');
      setPhonesValues(phonesValuesResponse.data);
      const patientValuesResponse = await axios.get('/api/responsibles/patientValues');
      setPatientValues(patientValuesResponse.data);
      const data = (await axios.get('/api/responsibles/' + currentId)).data;
      useFormResult.reset(data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareForm();
  }, []);

  const updateResponsible = async (data: ResponsibleDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.put('/api/responsibles/' + currentId, data);
      navigate('/responsibles', {
            state: {
              msgSuccess: t('responsible.update.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('responsible.edit.headline')}</h1>
      <div>
        <Link to="/responsibles" className="btn btn-secondary">{t('responsible.edit.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(updateResponsible)} noValidate>
      <InputRow useFormResult={useFormResult} object="responsible" field="id" disabled={true} type="number" />
      <InputRow useFormResult={useFormResult} object="responsible" field="name" />
      <InputRow useFormResult={useFormResult} object="responsible" field="degreeOfRelatedness" />
      <InputRow useFormResult={useFormResult} object="responsible" field="phones" required={true} type="select" options={phonesValues} />
      <InputRow useFormResult={useFormResult} object="responsible" field="patient" required={true} type="select" options={patientValues} />
      <input type="submit" value={t('responsible.edit.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/responsible/responsible-edit.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { ResponsibleService } from 'app/responsible/responsible.service';
import { ResponsibleDTO } from 'app/responsible/responsible.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { updateForm } from 'app/common/utils';


@Component({
  selector: 'app-responsible-edit',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './responsible-edit.component.html'
})
export class ResponsibleEditComponent implements OnInit {

  responsibleService = inject(ResponsibleService);
  route = inject(ActivatedRoute);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  phonesValues?: Map<number,string>;
  patientValues?: Map<number,string>;
  currentId?: number;

  editForm = new FormGroup({
    id: new FormControl({ value: null, disabled: true }),
    name: new FormControl(null, [Validators.maxLength(255)]),
    degreeOfRelatedness: new FormControl(null, [Validators.maxLength(255)]),
    phones: new FormControl(null, [Validators.required]),
    patient: new FormControl(null, [Validators.required])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      updated: $localize`:@@responsible.update.success:Responsible was updated successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.currentId = +this.route.snapshot.params['id'];
    this.responsibleService.getPhonesValues()
        .subscribe({
          next: (data) => this.phonesValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.responsibleService.getPatientValues()
        .subscribe({
          next: (data) => this.patientValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.responsibleService.getResponsible(this.currentId!)
        .subscribe({
          next: (data) => updateForm(this.editForm, data),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.editForm.markAllAsTouched();
    if (!this.editForm.valid) {
      return;
    }
    const data = new ResponsibleDTO(this.editForm.value);
    this.responsibleService.updateResponsible(this.currentId!, data)
        .subscribe({
          next: () => this.router.navigate(['/responsibles'], {
            state: {
              msgSuccess: this.getMessage('updated')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.editForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@responsible.edit.headline">Edit Responsible</h1>
    <div>
        <a routerLink="/responsibles" class="btn btn-secondary" i18n="@@responsible.edit.back">Back to list</a>
    </div>
</div>
<form [formGroup]="editForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="editForm" field="id" rowType="number" i18n-label="@@responsible.id.label" label="Id" />
    <app-input-row [group]="editForm" field="name" i18n-label="@@responsible.name.label" label="Name" />
    <app-input-row [group]="editForm" field="degreeOfRelatedness" i18n-label="@@responsible.degreeOfRelatedness.label" label="Degree Of Relatedness" />
    <app-input-row [group]="editForm" field="phones" rowType="select" [options]="phonesValues" i18n-label="@@responsible.phones.label" label="Phones" />
    <app-input-row [group]="editForm" field="patient" rowType="select" [options]="patientValues" i18n-label="@@responsible.patient.label" label="Patient" />
    <input type="submit" i18n-value="@@responsible.edit.headline" value="Edit Responsible" class="btn btn-primary mt-4" />
</form>
