// src/main/webapp/app/doctor/doctor-edit.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { DoctorService } from 'app/doctor/doctor.service';
import { DoctorDTO } from 'app/doctor/doctor.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { updateForm } from 'app/common/utils';


@Component({
  selector: 'app-doctor-edit',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './doctor-edit.component.html'
})
export class DoctorEditComponent implements OnInit {

  doctorService = inject(DoctorService);
  route = inject(ActivatedRoute);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  userValues?: Map<number,string>;
  specialtyValues?: Map<number,string>;
  healthinsurancesValues?: Map<number,string>;
  documentsValues?: Map<number,string>;
  currentId?: number;

  editForm = new FormGroup({
    id: new FormControl({ value: null, disabled: true }),
    conselho: new FormControl(null, [Validators.maxLength(255)]),
    ufconselho: new FormControl(null, [Validators.maxLength(255)]),
    registro: new FormControl(null, [Validators.maxLength(255)]),
    title: new FormControl(null, [Validators.maxLength(255)]),
    user: new FormControl(null),
    specialty: new FormControl(null),
    healthinsurances: new FormControl([]),
    documents: new FormControl([])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      updated: $localize`:@@doctor.update.success:Doctor was updated successfully.`,
      DOCTOR_USER_UNIQUE: $localize`:@@Exists.doctor.user:This User is already referenced by another Doctor.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.currentId = +this.route.snapshot.params['id'];
    this.doctorService.getUserValues()
        .subscribe({
          next: (data) => this.userValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.doctorService.getSpecialtyValues()
        .subscribe({
          next: (data) => this.specialtyValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.doctorService.getHealthinsurancesValues()
        .subscribe({
          next: (data) => this.healthinsurancesValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.doctorService.getDocumentsValues()
        .subscribe({
          next: (data) => this.documentsValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.doctorService.getDoctor(this.currentId!)
        .subscribe({
          next: (data) => updateForm(this.editForm, data),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.editForm.markAllAsTouched();
    if (!this.editForm.valid) {
      return;
    }
    const data = new DoctorDTO(this.editForm.value);
    this.doctorService.updateDoctor(this.currentId!, data)
        .subscribe({
          next: () => this.router.navigate(['/doctors'], {
            state: {
              msgSuccess: this.getMessage('updated')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.editForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@doctor.edit.headline">Edit Doctor</h1>
    <div>
        <a routerLink="/doctors" class="btn btn-secondary" i18n="@@doctor.edit.back">Back to list</a>
    </div>
</div>
<form [formGroup]="editForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="editForm" field="id" rowType="number" i18n-label="@@doctor.id.label" label="Id" />
    <app-input-row [group]="editForm" field="conselho" i18n-label="@@doctor.conselho.label" label="Conselho" />
    <app-input-row [group]="editForm" field="ufconselho" i18n-label="@@doctor.ufconselho.label" label="Ufconselho" />
    <app-input-row [group]="editForm" field="registro" i18n-label="@@doctor.registro.label" label="Registro" />
    <app-input-row [group]="editForm" field="title" i18n-label="@@doctor.title.label" label="Title" />
    <app-input-row [group]="editForm" field="user" rowType="select" [options]="userValues" i18n-label="@@doctor.user.label" label="User" />
    <app-input-row [group]="editForm" field="specialty" rowType="select" [options]="specialtyValues" i18n-label="@@doctor.specialty.label" label="Specialty" />
    <app-input-row [group]="editForm" field="healthinsurances" rowType="multiselect" [options]="healthinsurancesValues" i18n-label="@@doctor.healthinsurances.label" label="Healthinsurances" />
    <app-input-row [group]="editForm" field="documents" rowType="multiselect" [options]="documentsValues" i18n-label="@@doctor.documents.label" label="Documents" />
    <input type="submit" i18n-value="@@doctor.edit.headline" value="Edit Doctor" class="btn btn-primary mt-4" />
</form>

// src/main/webapp/app/doctor/doctor-edit.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate, useParams } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { DoctorDTO } from 'app/doctor/doctor-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    conselho: yup.string().emptyToNull().max(255),
    ufconselho: yup.string().emptyToNull().max(255),
    registro: yup.string().emptyToNull().max(255),
    title: yup.string().emptyToNull().max(255),
    user: yup.number().integer().emptyToNull(),
    specialty: yup.number().integer().emptyToNull(),
    healthinsurances: yup.array(yup.number().required()).emptyToNull().json(),
    documents: yup.array(yup.number().required()).emptyToNull().json()
  });
}

export default function DoctorEdit() {
  const { t } = useTranslation();
  useDocumentTitle(t('doctor.edit.headline'));

  const navigate = useNavigate();
  const [userValues, setUserValues] = useState<Map<number,string>>(new Map());
  const [specialtyValues, setSpecialtyValues] = useState<Map<number,string>>(new Map());
  const [healthinsurancesValues, setHealthinsurancesValues] = useState<Map<number,string>>(new Map());
  const [documentsValues, setDocumentsValues] = useState<Map<number,string>>(new Map());
  const params = useParams();
  const currentId = +params.id!;

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const getMessage = (key: string) => {
    const messages: Record<string, string> = {
      DOCTOR_USER_UNIQUE: t('Exists.doctor.user')
    };
    return messages[key];
  };

  const prepareForm = async () => {
    try {
      const userValuesResponse = await axios.get('/api/doctors/userValues');
      setUserValues(userValuesResponse.data);
      const specialtyValuesResponse = await axios.get('/api/doctors/specialtyValues');
      setSpecialtyValues(specialtyValuesResponse.data);
      const healthinsurancesValuesResponse = await axios.get('/api/doctors/healthinsurancesValues');
      setHealthinsurancesValues(healthinsurancesValuesResponse.data);
      const documentsValuesResponse = await axios.get('/api/doctors/documentsValues');
      setDocumentsValues(documentsValuesResponse.data);
      const data = (await axios.get('/api/doctors/' + currentId)).data;
      if (data.healthinsurances) {
        data.healthinsurances = JSON.stringify(data.healthinsurances, undefined, 2);
      }
      if (data.documents) {
        data.documents = JSON.stringify(data.documents, undefined, 2);
      }
      useFormResult.reset(data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareForm();
  }, []);

  const updateDoctor = async (data: DoctorDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.put('/api/doctors/' + currentId, data);
      navigate('/doctors', {
            state: {
              msgSuccess: t('doctor.update.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t, getMessage);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('doctor.edit.headline')}</h1>
      <div>
        <Link to="/doctors" className="btn btn-secondary">{t('doctor.edit.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(updateDoctor)} noValidate>
      <InputRow useFormResult={useFormResult} object="doctor" field="id" disabled={true} type="number" />
      <InputRow useFormResult={useFormResult} object="doctor" field="conselho" />
      <InputRow useFormResult={useFormResult} object="doctor" field="ufconselho" />
      <InputRow useFormResult={useFormResult} object="doctor" field="registro" />
      <InputRow useFormResult={useFormResult} object="doctor" field="title" />
      <InputRow useFormResult={useFormResult} object="doctor" field="user" type="select" options={userValues} />
      <InputRow useFormResult={useFormResult} object="doctor" field="specialty" type="select" options={specialtyValues} />
      <InputRow useFormResult={useFormResult} object="doctor" field="healthinsurances" type="multiselect" options={healthinsurancesValues} />
      <InputRow useFormResult={useFormResult} object="doctor" field="documents" type="multiselect" options={documentsValues} />
      <input type="submit" value={t('doctor.edit.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}
