// src/main/webapp/app/doctor/doctor-add.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { DoctorService } from 'app/doctor/doctor.service';
import { DoctorDTO } from 'app/doctor/doctor.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';


@Component({
  selector: 'app-doctor-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './doctor-add.component.html'
})
export class DoctorAddComponent implements OnInit {

  doctorService = inject(DoctorService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  userValues?: Map<number,string>;
  specialtyValues?: Map<number,string>;
  healthinsurancesValues?: Map<number,string>;
  documentsValues?: Map<number,string>;

  addForm = new FormGroup({
    conselho: new FormControl(null, [Validators.maxLength(255)]),
    ufconselho: new FormControl(null, [Validators.maxLength(255)]),
    registro: new FormControl(null, [Validators.maxLength(255)]),
    title: new FormControl(null, [Validators.maxLength(255)]),
    user: new FormControl(null),
    specialty: new FormControl(null),
    healthinsurances: new FormControl([]),
    documents: new FormControl([])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@doctor.create.success:Doctor was created successfully.`,
      DOCTOR_USER_UNIQUE: $localize`:@@Exists.doctor.user:This User is already referenced by another Doctor.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.doctorService.getUserValues()
        .subscribe({
          next: (data) => this.userValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.doctorService.getSpecialtyValues()
        .subscribe({
          next: (data) => this.specialtyValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.doctorService.getHealthinsurancesValues()
        .subscribe({
          next: (data) => this.healthinsurancesValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.doctorService.getDocumentsValues()
        .subscribe({
          next: (data) => this.documentsValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new DoctorDTO(this.addForm.value);
    this.doctorService.createDoctor(data)
        .subscribe({
          next: () => this.router.navigate(['/doctors'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@doctor.add.headline">Add Doctor</h1>
    <div>
        <a routerLink="/doctors" class="btn btn-secondary" i18n="@@doctor.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="conselho" i18n-label="@@doctor.conselho.label" label="Conselho" />
    <app-input-row [group]="addForm" field="ufconselho" i18n-label="@@doctor.ufconselho.label" label="Ufconselho" />
    <app-input-row [group]="addForm" field="registro" i18n-label="@@doctor.registro.label" label="Registro" />
    <app-input-row [group]="addForm" field="title" i18n-label="@@doctor.title.label" label="Title" />
    <app-input-row [group]="addForm" field="user" rowType="select" [options]="userValues" i18n-label="@@doctor.user.label" label="User" />
    <app-input-row [group]="addForm" field="specialty" rowType="select" [options]="specialtyValues" i18n-label="@@doctor.specialty.label" label="Specialty" />
    <app-input-row [group]="addForm" field="healthinsurances" rowType="multiselect" [options]="healthinsurancesValues" i18n-label="@@doctor.healthinsurances.label" label="Healthinsurances" />
    <app-input-row [group]="addForm" field="documents" rowType="multiselect" [options]="documentsValues" i18n-label="@@doctor.documents.label" label="Documents" />
    <input type="submit" i18n-value="@@doctor.add.headline" value="Add Doctor" class="btn btn-primary mt-4" />
</form>

// src/main/webapp/app/doctor/doctor-add.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { DoctorDTO } from 'app/doctor/doctor-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    conselho: yup.string().emptyToNull().max(255),
    ufconselho: yup.string().emptyToNull().max(255),
    registro: yup.string().emptyToNull().max(255),
    title: yup.string().emptyToNull().max(255),
    user: yup.number().integer().emptyToNull(),
    specialty: yup.number().integer().emptyToNull(),
    healthinsurances: yup.array(yup.number().required()).emptyToNull().json(),
    documents: yup.array(yup.number().required()).emptyToNull().json()
  });
}

export default function DoctorAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('doctor.add.headline'));

  const navigate = useNavigate();
  const [userValues, setUserValues] = useState<Map<number,string>>(new Map());
  const [specialtyValues, setSpecialtyValues] = useState<Map<number,string>>(new Map());
  const [healthinsurancesValues, setHealthinsurancesValues] = useState<Map<number,string>>(new Map());
  const [documentsValues, setDocumentsValues] = useState<Map<number,string>>(new Map());

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const getMessage = (key: string) => {
    const messages: Record<string, string> = {
      DOCTOR_USER_UNIQUE: t('Exists.doctor.user')
    };
    return messages[key];
  };

  const prepareRelations = async () => {
    try {
      const userValuesResponse = await axios.get('/api/doctors/userValues');
      setUserValues(userValuesResponse.data);
      const specialtyValuesResponse = await axios.get('/api/doctors/specialtyValues');
      setSpecialtyValues(specialtyValuesResponse.data);
      const healthinsurancesValuesResponse = await axios.get('/api/doctors/healthinsurancesValues');
      setHealthinsurancesValues(healthinsurancesValuesResponse.data);
      const documentsValuesResponse = await axios.get('/api/doctors/documentsValues');
      setDocumentsValues(documentsValuesResponse.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareRelations();
  }, []);

  const createDoctor = async (data: DoctorDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/doctors', data);
      navigate('/doctors', {
            state: {
              msgSuccess: t('doctor.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t, getMessage);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('doctor.add.headline')}</h1>
      <div>
        <Link to="/doctors" className="btn btn-secondary">{t('doctor.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createDoctor)} noValidate>
      <InputRow useFormResult={useFormResult} object="doctor" field="conselho" />
      <InputRow useFormResult={useFormResult} object="doctor" field="ufconselho" />
      <InputRow useFormResult={useFormResult} object="doctor" field="registro" />
      <InputRow useFormResult={useFormResult} object="doctor" field="title" />
      <InputRow useFormResult={useFormResult} object="doctor" field="user" type="select" options={userValues} />
      <InputRow useFormResult={useFormResult} object="doctor" field="specialty" type="select" options={specialtyValues} />
      <InputRow useFormResult={useFormResult} object="doctor" field="healthinsurances" type="multiselect" options={healthinsurancesValues} />
      <InputRow useFormResult={useFormResult} object="doctor" field="documents" type="multiselect" options={documentsValues} />
      <input type="submit" value={t('doctor.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}
