// src/main/webapp/app/doctor/doctor-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { DoctorService } from 'app/doctor/doctor.service';
import { DoctorDTO } from 'app/doctor/doctor.model';


@Component({
  selector: 'app-doctor-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './doctor-list.component.html'})
export class DoctorListComponent implements OnInit, OnDestroy {

  doctorService = inject(DoctorService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  doctors?: DoctorDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@doctor.delete.success:Doctor was removed successfully.`,
      'doctor.doctorsAvailableSchedule.doctor.referenced': $localize`:@@doctor.doctorsAvailableSchedule.doctor.referenced:This entity is still referenced by Doctors Available Schedule ${details?.id} via field Doctor.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.doctorService.getAllDoctors()
        .subscribe({
          next: (data) => this.doctors = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.doctorService.deleteDoctor(id)
        .subscribe({
          next: () => this.router.navigate(['/doctors'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => {
            if (error.error?.code === 'REFERENCED') {
              const messageParts = error.error.message.split(',');
              this.router.navigate(['/doctors'], {
                state: {
                  msgError: this.getMessage(messageParts[0], { id: messageParts[1] })
                }
              });
              return;
            }
            this.errorHandler.handleServerError(error.error)
          }
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@doctor.list.headline">Doctors</h1>
    <div>
        <a routerLink="/doctors/add" class="btn btn-primary ms-2" i18n="@@doctor.list.createNew">Create new Doctor</a>
    </div>
</div>
@if (!doctors || doctors.length === 0) {
<div i18n="@@doctor.list.empty">No Doctors could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@doctor.id.label">Id</th>
                <th scope="col" i18n="@@doctor.conselho.label">Conselho</th>
                <th scope="col" i18n="@@doctor.ufconselho.label">Ufconselho</th>
                <th scope="col" i18n="@@doctor.registro.label">Registro</th>
                <th scope="col" i18n="@@doctor.title.label">Title</th>
                <th scope="col" i18n="@@doctor.user.label">User</th>
                <th scope="col" i18n="@@doctor.specialty.label">Specialty</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (doctor of doctors; track doctor.id) {
            <tr>
                <td>{{ doctor.id }}</td>
                <td>{{ doctor.conselho }}</td>
                <td>{{ doctor.ufconselho }}</td>
                <td>{{ doctor.registro }}</td>
                <td>{{ doctor.title }}</td>
                <td>{{ doctor.user }}</td>
                <td>{{ doctor.specialty }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/doctors/edit', doctor.id]" class="btn btn-sm btn-secondary" i18n="@@doctor.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(doctor.id!)" class="btn btn-sm btn-secondary" i18n="@@doctor.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}

// src/main/webapp/app/doctor/doctor-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { DoctorDTO } from 'app/doctor/doctor-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function DoctorList() {
  const { t } = useTranslation();
  useDocumentTitle(t('doctor.list.headline'));

  const [doctors, setDoctors] = useState<DoctorDTO[]>([]);
  const navigate = useNavigate();

  const getAllDoctors = async () => {
    try {
      const response = await axios.get('/api/doctors');
      setDoctors(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/doctors/' + id);
      navigate('/doctors', {
            state: {
              msgInfo: t('doctor.delete.success')
            }
          });
      getAllDoctors();
    } catch (error: any) {
      if (error?.response?.data?.code === 'REFERENCED') {
        const messageParts = error.response.data.message.split(',');
        navigate('/doctors', {
              state: {
                msgError: t(messageParts[0]!, { id: messageParts[1]! })
              }
            });
        return;
      }
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllDoctors();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('doctor.list.headline')}</h1>
      <div>
        <Link to="/doctors/add" className="btn btn-primary ms-2">{t('doctor.list.createNew')}</Link>
      </div>
    </div>
    {!doctors || doctors.length === 0 ? (
    <div>{t('doctor.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('doctor.id.label')}</th>
            <th scope="col">{t('doctor.conselho.label')}</th>
            <th scope="col">{t('doctor.ufconselho.label')}</th>
            <th scope="col">{t('doctor.registro.label')}</th>
            <th scope="col">{t('doctor.title.label')}</th>
            <th scope="col">{t('doctor.user.label')}</th>
            <th scope="col">{t('doctor.specialty.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {doctors.map((doctor) => (
          <tr key={doctor.id}>
            <td>{doctor.id}</td>
            <td>{doctor.conselho}</td>
            <td>{doctor.ufconselho}</td>
            <td>{doctor.registro}</td>
            <td>{doctor.title}</td>
            <td>{doctor.user}</td>
            <td>{doctor.specialty}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/doctors/edit/' + doctor.id} className="btn btn-sm btn-secondary">{t('doctor.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(doctor.id!)} className="btn btn-sm btn-secondary">{t('doctor.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}
