// src/main/webapp/app/emails/emails-edit.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { EmailsService } from 'app/emails/emails.service';
import { EmailsDTO } from 'app/emails/emails.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { updateForm } from 'app/common/utils';


@Component({
  selector: 'app-emails-edit',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './emails-edit.component.html'
})
export class EmailsEditComponent implements OnInit {

  emailsService = inject(EmailsService);
  route = inject(ActivatedRoute);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  newsletterValues?: Map<number,string>;
  currentId?: number;

  editForm = new FormGroup({
    id: new FormControl({ value: null, disabled: true }),
    email: new FormControl(null, [Validators.maxLength(255)]),
    active: new FormControl(false),
    newsletter: new FormControl(null)
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      updated: $localize`:@@emails.update.success:Emails was updated successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.currentId = +this.route.snapshot.params['id'];
    this.emailsService.getNewsletterValues()
        .subscribe({
          next: (data) => this.newsletterValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.emailsService.getEmails(this.currentId!)
        .subscribe({
          next: (data) => updateForm(this.editForm, data),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.editForm.markAllAsTouched();
    if (!this.editForm.valid) {
      return;
    }
    const data = new EmailsDTO(this.editForm.value);
    this.emailsService.updateEmails(this.currentId!, data)
        .subscribe({
          next: () => this.router.navigate(['/emailss'], {
            state: {
              msgSuccess: this.getMessage('updated')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.editForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@emails.edit.headline">Edit Emails</h1>
    <div>
        <a routerLink="/emailss" class="btn btn-secondary" i18n="@@emails.edit.back">Back to list</a>
    </div>
</div>
<form [formGroup]="editForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="editForm" field="id" rowType="number" i18n-label="@@emails.id.label" label="Id" />
    <app-input-row [group]="editForm" field="email" i18n-label="@@emails.email.label" label="Email" />
    <app-input-row [group]="editForm" field="active" rowType="checkbox" i18n-label="@@emails.active.label" label="Active" />
    <app-input-row [group]="editForm" field="newsletter" rowType="select" [options]="newsletterValues" i18n-label="@@emails.newsletter.label" label="Newsletter" />
    <input type="submit" i18n-value="@@emails.edit.headline" value="Edit Emails" class="btn btn-primary mt-4" />
</form>

// src/main/webapp/app/emails/emails-edit.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate, useParams } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { EmailsDTO } from 'app/emails/emails-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    email: yup.string().emptyToNull().max(255),
    active: yup.bool(),
    newsletter: yup.number().integer().emptyToNull()
  });
}

export default function EmailsEdit() {
  const { t } = useTranslation();
  useDocumentTitle(t('emails.edit.headline'));

  const navigate = useNavigate();
  const [newsletterValues, setNewsletterValues] = useState<Map<number,string>>(new Map());
  const params = useParams();
  const currentId = +params.id!;

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareForm = async () => {
    try {
      const newsletterValuesResponse = await axios.get('/api/emailss/newsletterValues');
      setNewsletterValues(newsletterValuesResponse.data);
      const data = (await axios.get('/api/emailss/' + currentId)).data;
      useFormResult.reset(data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareForm();
  }, []);

  const updateEmails = async (data: EmailsDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.put('/api/emailss/' + currentId, data);
      navigate('/emailss', {
            state: {
              msgSuccess: t('emails.update.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('emails.edit.headline')}</h1>
      <div>
        <Link to="/emailss" className="btn btn-secondary">{t('emails.edit.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(updateEmails)} noValidate>
      <InputRow useFormResult={useFormResult} object="emails" field="id" disabled={true} type="number" />
      <InputRow useFormResult={useFormResult} object="emails" field="email" />
      <InputRow useFormResult={useFormResult} object="emails" field="active" type="checkbox" />
      <InputRow useFormResult={useFormResult} object="emails" field="newsletter" type="select" options={newsletterValues} />
      <input type="submit" value={t('emails.edit.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}
