// src/main/webapp/app/emails/emails-add.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { EmailsDTO } from 'app/emails/emails-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    email: yup.string().emptyToNull().max(255),
    active: yup.bool(),
    newsletter: yup.number().integer().emptyToNull()
  });
}

export default function EmailsAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('emails.add.headline'));

  const navigate = useNavigate();
  const [newsletterValues, setNewsletterValues] = useState<Map<number,string>>(new Map());

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareRelations = async () => {
    try {
      const newsletterValuesResponse = await axios.get('/api/emailss/newsletterValues');
      setNewsletterValues(newsletterValuesResponse.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareRelations();
  }, []);

  const createEmails = async (data: EmailsDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/emailss', data);
      navigate('/emailss', {
            state: {
              msgSuccess: t('emails.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('emails.add.headline')}</h1>
      <div>
        <Link to="/emailss" className="btn btn-secondary">{t('emails.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createEmails)} noValidate>
      <InputRow useFormResult={useFormResult} object="emails" field="email" />
      <InputRow useFormResult={useFormResult} object="emails" field="active" type="checkbox" />
      <InputRow useFormResult={useFormResult} object="emails" field="newsletter" type="select" options={newsletterValues} />
      <input type="submit" value={t('emails.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/emails/emails-add.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { EmailsService } from 'app/emails/emails.service';
import { EmailsDTO } from 'app/emails/emails.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';


@Component({
  selector: 'app-emails-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './emails-add.component.html'
})
export class EmailsAddComponent implements OnInit {

  emailsService = inject(EmailsService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  newsletterValues?: Map<number,string>;

  addForm = new FormGroup({
    email: new FormControl(null, [Validators.maxLength(255)]),
    active: new FormControl(false),
    newsletter: new FormControl(null)
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@emails.create.success:Emails was created successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.emailsService.getNewsletterValues()
        .subscribe({
          next: (data) => this.newsletterValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new EmailsDTO(this.addForm.value);
    this.emailsService.createEmails(data)
        .subscribe({
          next: () => this.router.navigate(['/emailss'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@emails.add.headline">Add Emails</h1>
    <div>
        <a routerLink="/emailss" class="btn btn-secondary" i18n="@@emails.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="email" i18n-label="@@emails.email.label" label="Email" />
    <app-input-row [group]="addForm" field="active" rowType="checkbox" i18n-label="@@emails.active.label" label="Active" />
    <app-input-row [group]="addForm" field="newsletter" rowType="select" [options]="newsletterValues" i18n-label="@@emails.newsletter.label" label="Newsletter" />
    <input type="submit" i18n-value="@@emails.add.headline" value="Add Emails" class="btn btn-primary mt-4" />
</form>
