// src/main/webapp/app/emails/emails-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { EmailsDTO } from 'app/emails/emails-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function EmailsList() {
  const { t } = useTranslation();
  useDocumentTitle(t('emails.list.headline'));

  const [emailses, setEmailses] = useState<EmailsDTO[]>([]);
  const navigate = useNavigate();

  const getAllEmailses = async () => {
    try {
      const response = await axios.get('/api/emailss');
      setEmailses(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/emailss/' + id);
      navigate('/emailss', {
            state: {
              msgInfo: t('emails.delete.success')
            }
          });
      getAllEmailses();
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllEmailses();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('emails.list.headline')}</h1>
      <div>
        <Link to="/emailss/add" className="btn btn-primary ms-2">{t('emails.list.createNew')}</Link>
      </div>
    </div>
    {!emailses || emailses.length === 0 ? (
    <div>{t('emails.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('emails.id.label')}</th>
            <th scope="col">{t('emails.email.label')}</th>
            <th scope="col">{t('emails.active.label')}</th>
            <th scope="col">{t('emails.newsletter.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {emailses.map((emails) => (
          <tr key={emails.id}>
            <td>{emails.id}</td>
            <td>{emails.email}</td>
            <td>{emails.active?.toString()}</td>
            <td>{emails.newsletter}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/emailss/edit/' + emails.id} className="btn btn-sm btn-secondary">{t('emails.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(emails.id!)} className="btn btn-sm btn-secondary">{t('emails.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}

// src/main/webapp/app/emails/emails-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { EmailsService } from 'app/emails/emails.service';
import { EmailsDTO } from 'app/emails/emails.model';


@Component({
  selector: 'app-emails-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './emails-list.component.html'})
export class EmailsListComponent implements OnInit, OnDestroy {

  emailsService = inject(EmailsService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  emailses?: EmailsDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@emails.delete.success:Emails was removed successfully.`    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.emailsService.getAllEmailses()
        .subscribe({
          next: (data) => this.emailses = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.emailsService.deleteEmails(id)
        .subscribe({
          next: () => this.router.navigate(['/emailss'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@emails.list.headline">Emailses</h1>
    <div>
        <a routerLink="/emailss/add" class="btn btn-primary ms-2" i18n="@@emails.list.createNew">Create new Emails</a>
    </div>
</div>
@if (!emailses || emailses.length === 0) {
<div i18n="@@emails.list.empty">No Emailses could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@emails.id.label">Id</th>
                <th scope="col" i18n="@@emails.email.label">Email</th>
                <th scope="col" i18n="@@emails.active.label">Active</th>
                <th scope="col" i18n="@@emails.newsletter.label">Newsletter</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (emails of emailses; track emails.id) {
            <tr>
                <td>{{ emails.id }}</td>
                <td>{{ emails.email }}</td>
                <td>{{ emails.active }}</td>
                <td>{{ emails.newsletter }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/emailss/edit', emails.id]" class="btn btn-sm btn-secondary" i18n="@@emails.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(emails.id!)" class="btn btn-sm btn-secondary" i18n="@@emails.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}
