// src/main/webapp/app/role/role-add.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { RoleDTO } from 'app/role/role-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    type: yup.string().emptyToNull().max(255).required()
  });
}

export default function RoleAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('role.add.headline'));

  const navigate = useNavigate();

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const getMessage = (key: string) => {
    const messages: Record<string, string> = {
      ROLE_TYPE_UNIQUE: t('exists.role.type')
    };
    return messages[key];
  };

  const createRole = async (data: RoleDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/roles', data);
      navigate('/roles', {
            state: {
              msgSuccess: t('role.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t, getMessage);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('role.add.headline')}</h1>
      <div>
        <Link to="/roles" className="btn btn-secondary">{t('role.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createRole)} noValidate>
      <InputRow useFormResult={useFormResult} object="role" field="type" required={true} />
      <input type="submit" value={t('role.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/role/role-add.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { RoleService } from 'app/role/role.service';
import { RoleDTO } from 'app/role/role.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';


@Component({
  selector: 'app-role-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './role-add.component.html'
})
export class RoleAddComponent {

  roleService = inject(RoleService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  addForm = new FormGroup({
    type: new FormControl(null, [Validators.required])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@role.create.success:Role was created successfully.`,
      ROLE_TYPE_UNIQUE: $localize`:@@Exists.role.type:This Role Type is already taken.`
    };
    return messages[key];
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new RoleDTO(this.addForm.value);
    this.roleService.createRole(data)
        .subscribe({
          next: () => this.router.navigate(['/roles'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@role.add.headline">Add Role</h1>
    <div>
        <a routerLink="/roles" class="btn btn-secondary" i18n="@@role.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="type" rowType="radio" [options]="{'PATIENT': 'PATIENT', 'DOCTOR': 'DOCTOR', 'ADMIN': 'ADMIN'}" i18n-label="@@role.type.label" label="Type" />
    <input type="submit" i18n-value="@@role.add.headline" value="Add Role" class="btn btn-primary mt-4" />
</form>
