// src/main/webapp/app/role/role-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { RoleDTO } from 'app/role/role-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function RoleList() {
  const { t } = useTranslation();
  useDocumentTitle(t('role.list.headline'));

  const [roles, setRoles] = useState<RoleDTO[]>([]);
  const navigate = useNavigate();

  const getAllRoles = async () => {
    try {
      const response = await axios.get('/api/roles');
      setRoles(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/roles/' + id);
      navigate('/roles', {
            state: {
              msgInfo: t('role.delete.success')
            }
          });
      getAllRoles();
    } catch (error: any) {
      if (error?.response?.data?.code === 'REFERENCED') {
        const messageParts = error.response.data.message.split(',');
        navigate('/roles', {
              state: {
                msgError: t(messageParts[0]!, { id: messageParts[1]! })
              }
            });
        return;
      }
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllRoles();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('role.list.headline')}</h1>
      <div>
        <Link to="/roles/add" className="btn btn-primary ms-2">{t('role.list.createNew')}</Link>
      </div>
    </div>
    {!roles || roles.length === 0 ? (
    <div>{t('role.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('role.id.label')}</th>
            <th scope="col">{t('role.type.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {roles.map((role) => (
          <tr key={role.id}>
            <td>{role.id}</td>
            <td>{role.type}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/roles/edit/' + role.id} className="btn btn-sm btn-secondary">{t('role.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(role.id!)} className="btn btn-sm btn-secondary">{t('role.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}

// src/main/webapp/app/role/role-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { RoleService } from 'app/role/role.service';
import { RoleDTO } from 'app/role/role.model';


@Component({
  selector: 'app-role-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './role-list.component.html'})
export class RoleListComponent implements OnInit, OnDestroy {

  roleService = inject(RoleService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  roles?: RoleDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@role.delete.success:Role was removed successfully.`,
      'role.user.role.referenced': $localize`:@@role.user.role.referenced:This entity is still referenced by User ${details?.id} via field Role.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.roleService.getAllRoles()
        .subscribe({
          next: (data) => this.roles = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.roleService.deleteRole(id)
        .subscribe({
          next: () => this.router.navigate(['/roles'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => {
            if (error.error?.code === 'REFERENCED') {
              const messageParts = error.error.message.split(',');
              this.router.navigate(['/roles'], {
                state: {
                  msgError: this.getMessage(messageParts[0], { id: messageParts[1] })
                }
              });
              return;
            }
            this.errorHandler.handleServerError(error.error)
          }
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@role.list.headline">Roles</h1>
    <div>
        <a routerLink="/roles/add" class="btn btn-primary ms-2" i18n="@@role.list.createNew">Create new Role</a>
    </div>
</div>
@if (!roles || roles.length === 0) {
<div i18n="@@role.list.empty">No Roles could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@role.id.label">Id</th>
                <th scope="col" i18n="@@role.type.label">Type</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (role of roles; track role.id) {
            <tr>
                <td>{{ role.id }}</td>
                <td>{{ role.type }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/roles/edit', role.id]" class="btn btn-sm btn-secondary" i18n="@@role.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(role.id!)" class="btn btn-sm btn-secondary" i18n="@@role.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}
