// src/main/webapp/app/medical-record/medical-record-add.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { MedicalRecordDTO } from 'app/medical-record/medical-record-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    notes: yup.string().emptyToNull(),
    schedule: yup.number().integer().emptyToNull()
  });
}

export default function MedicalRecordAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('medicalRecord.add.headline'));

  const navigate = useNavigate();
  const [scheduleValues, setScheduleValues] = useState<Map<number,string>>(new Map());

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const getMessage = (key: string) => {
    const messages: Record<string, string> = {
      MEDICAL_RECORD_SCHEDULE_UNIQUE: t('Exists.medicalRecord.schedule')
    };
    return messages[key];
  };

  const prepareRelations = async () => {
    try {
      const scheduleValuesResponse = await axios.get('/api/medicalRecords/scheduleValues');
      setScheduleValues(scheduleValuesResponse.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareRelations();
  }, []);

  const createMedicalRecord = async (data: MedicalRecordDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/medicalRecords', data);
      navigate('/medicalRecords', {
            state: {
              msgSuccess: t('medicalRecord.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t, getMessage);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('medicalRecord.add.headline')}</h1>
      <div>
        <Link to="/medicalRecords" className="btn btn-secondary">{t('medicalRecord.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createMedicalRecord)} noValidate>
      <InputRow useFormResult={useFormResult} object="medicalRecord" field="notes" type="textarea" />
      <InputRow useFormResult={useFormResult} object="medicalRecord" field="schedule" type="select" options={scheduleValues} />
      <input type="submit" value={t('medicalRecord.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/medical-record/medical-record-add.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { MedicalRecordService } from 'app/medical-record/medical-record.service';
import { MedicalRecordDTO } from 'app/medical-record/medical-record.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';


@Component({
  selector: 'app-medical-record-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './medical-record-add.component.html'
})
export class MedicalRecordAddComponent implements OnInit {

  medicalRecordService = inject(MedicalRecordService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  scheduleValues?: Map<number,string>;

  addForm = new FormGroup({
    notes: new FormControl(null),
    schedule: new FormControl(null)
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@medicalRecord.create.success:Medical Record was created successfully.`,
      MEDICAL_RECORD_SCHEDULE_UNIQUE: $localize`:@@Exists.medicalRecord.schedule:This Schedule is already referenced by another Medical Record.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.medicalRecordService.getScheduleValues()
        .subscribe({
          next: (data) => this.scheduleValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new MedicalRecordDTO(this.addForm.value);
    this.medicalRecordService.createMedicalRecord(data)
        .subscribe({
          next: () => this.router.navigate(['/medicalRecords'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@medicalRecord.add.headline">Add Medical Record</h1>
    <div>
        <a routerLink="/medicalRecords" class="btn btn-secondary" i18n="@@medicalRecord.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="notes" rowType="textarea" i18n-label="@@medicalRecord.notes.label" label="Notes" />
    <app-input-row [group]="addForm" field="schedule" rowType="select" [options]="scheduleValues" i18n-label="@@medicalRecord.schedule.label" label="Schedule" />
    <input type="submit" i18n-value="@@medicalRecord.add.headline" value="Add Medical Record" class="btn btn-primary mt-4" />
</form>
