// src/main/webapp/app/medical-record/medical-record-edit.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { MedicalRecordService } from 'app/medical-record/medical-record.service';
import { MedicalRecordDTO } from 'app/medical-record/medical-record.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { updateForm } from 'app/common/utils';


@Component({
  selector: 'app-medical-record-edit',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './medical-record-edit.component.html'
})
export class MedicalRecordEditComponent implements OnInit {

  medicalRecordService = inject(MedicalRecordService);
  route = inject(ActivatedRoute);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  scheduleValues?: Map<number,string>;
  currentId?: number;

  editForm = new FormGroup({
    id: new FormControl({ value: null, disabled: true }),
    notes: new FormControl(null),
    schedule: new FormControl(null)
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      updated: $localize`:@@medicalRecord.update.success:Medical Record was updated successfully.`,
      MEDICAL_RECORD_SCHEDULE_UNIQUE: $localize`:@@Exists.medicalRecord.schedule:This Schedule is already referenced by another Medical Record.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.currentId = +this.route.snapshot.params['id'];
    this.medicalRecordService.getScheduleValues()
        .subscribe({
          next: (data) => this.scheduleValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.medicalRecordService.getMedicalRecord(this.currentId!)
        .subscribe({
          next: (data) => updateForm(this.editForm, data),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.editForm.markAllAsTouched();
    if (!this.editForm.valid) {
      return;
    }
    const data = new MedicalRecordDTO(this.editForm.value);
    this.medicalRecordService.updateMedicalRecord(this.currentId!, data)
        .subscribe({
          next: () => this.router.navigate(['/medicalRecords'], {
            state: {
              msgSuccess: this.getMessage('updated')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.editForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@medicalRecord.edit.headline">Edit Medical Record</h1>
    <div>
        <a routerLink="/medicalRecords" class="btn btn-secondary" i18n="@@medicalRecord.edit.back">Back to list</a>
    </div>
</div>
<form [formGroup]="editForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="editForm" field="id" rowType="number" i18n-label="@@medicalRecord.id.label" label="Id" />
    <app-input-row [group]="editForm" field="notes" rowType="textarea" i18n-label="@@medicalRecord.notes.label" label="Notes" />
    <app-input-row [group]="editForm" field="schedule" rowType="select" [options]="scheduleValues" i18n-label="@@medicalRecord.schedule.label" label="Schedule" />
    <input type="submit" i18n-value="@@medicalRecord.edit.headline" value="Edit Medical Record" class="btn btn-primary mt-4" />
</form>

// src/main/webapp/app/medical-record/medical-record-edit.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate, useParams } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { MedicalRecordDTO } from 'app/medical-record/medical-record-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    notes: yup.string().emptyToNull(),
    schedule: yup.number().integer().emptyToNull()
  });
}

export default function MedicalRecordEdit() {
  const { t } = useTranslation();
  useDocumentTitle(t('medicalRecord.edit.headline'));

  const navigate = useNavigate();
  const [scheduleValues, setScheduleValues] = useState<Map<number,string>>(new Map());
  const params = useParams();
  const currentId = +params.id!;

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const getMessage = (key: string) => {
    const messages: Record<string, string> = {
      MEDICAL_RECORD_SCHEDULE_UNIQUE: t('Exists.medicalRecord.schedule')
    };
    return messages[key];
  };

  const prepareForm = async () => {
    try {
      const scheduleValuesResponse = await axios.get('/api/medicalRecords/scheduleValues');
      setScheduleValues(scheduleValuesResponse.data);
      const data = (await axios.get('/api/medicalRecords/' + currentId)).data;
      useFormResult.reset(data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareForm();
  }, []);

  const updateMedicalRecord = async (data: MedicalRecordDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.put('/api/medicalRecords/' + currentId, data);
      navigate('/medicalRecords', {
            state: {
              msgSuccess: t('medicalRecord.update.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t, getMessage);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('medicalRecord.edit.headline')}</h1>
      <div>
        <Link to="/medicalRecords" className="btn btn-secondary">{t('medicalRecord.edit.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(updateMedicalRecord)} noValidate>
      <InputRow useFormResult={useFormResult} object="medicalRecord" field="id" disabled={true} type="number" />
      <InputRow useFormResult={useFormResult} object="medicalRecord" field="notes" type="textarea" />
      <InputRow useFormResult={useFormResult} object="medicalRecord" field="schedule" type="select" options={scheduleValues} />
      <input type="submit" value={t('medicalRecord.edit.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}
