// src/main/webapp/app/medical-record/medical-record-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { MedicalRecordDTO } from 'app/medical-record/medical-record-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function MedicalRecordList() {
  const { t } = useTranslation();
  useDocumentTitle(t('medicalRecord.list.headline'));

  const [medicalRecords, setMedicalRecords] = useState<MedicalRecordDTO[]>([]);
  const navigate = useNavigate();

  const getAllMedicalRecords = async () => {
    try {
      const response = await axios.get('/api/medicalRecords');
      setMedicalRecords(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/medicalRecords/' + id);
      navigate('/medicalRecords', {
            state: {
              msgInfo: t('medicalRecord.delete.success')
            }
          });
      getAllMedicalRecords();
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllMedicalRecords();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('medicalRecord.list.headline')}</h1>
      <div>
        <Link to="/medicalRecords/add" className="btn btn-primary ms-2">{t('medicalRecord.list.createNew')}</Link>
      </div>
    </div>
    {!medicalRecords || medicalRecords.length === 0 ? (
    <div>{t('medicalRecord.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('medicalRecord.id.label')}</th>
            <th scope="col">{t('medicalRecord.schedule.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {medicalRecords.map((medicalRecord) => (
          <tr key={medicalRecord.id}>
            <td>{medicalRecord.id}</td>
            <td>{medicalRecord.schedule}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/medicalRecords/edit/' + medicalRecord.id} className="btn btn-sm btn-secondary">{t('medicalRecord.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(medicalRecord.id!)} className="btn btn-sm btn-secondary">{t('medicalRecord.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}

// src/main/webapp/app/medical-record/medical-record-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { MedicalRecordService } from 'app/medical-record/medical-record.service';
import { MedicalRecordDTO } from 'app/medical-record/medical-record.model';


@Component({
  selector: 'app-medical-record-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './medical-record-list.component.html'})
export class MedicalRecordListComponent implements OnInit, OnDestroy {

  medicalRecordService = inject(MedicalRecordService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  medicalRecords?: MedicalRecordDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@medicalRecord.delete.success:Medical Record was removed successfully.`    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.medicalRecordService.getAllMedicalRecords()
        .subscribe({
          next: (data) => this.medicalRecords = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.medicalRecordService.deleteMedicalRecord(id)
        .subscribe({
          next: () => this.router.navigate(['/medicalRecords'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@medicalRecord.list.headline">Medical Records</h1>
    <div>
        <a routerLink="/medicalRecords/add" class="btn btn-primary ms-2" i18n="@@medicalRecord.list.createNew">Create new Medical Record</a>
    </div>
</div>
@if (!medicalRecords || medicalRecords.length === 0) {
<div i18n="@@medicalRecord.list.empty">No Medical Records could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@medicalRecord.id.label">Id</th>
                <th scope="col" i18n="@@medicalRecord.schedule.label">Schedule</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (medicalRecord of medicalRecords; track medicalRecord.id) {
            <tr>
                <td>{{ medicalRecord.id }}</td>
                <td>{{ medicalRecord.schedule }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/medicalRecords/edit', medicalRecord.id]" class="btn btn-sm btn-secondary" i18n="@@medicalRecord.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(medicalRecord.id!)" class="btn btn-sm btn-secondary" i18n="@@medicalRecord.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}
