// src/main/webapp/app/doctors-available-schedule/doctors-available-schedule-add.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { DoctorsAvailableScheduleService } from 'app/doctors-available-schedule/doctors-available-schedule.service';
import { DoctorsAvailableScheduleDTO } from 'app/doctors-available-schedule/doctors-available-schedule.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';


@Component({
  selector: 'app-doctors-available-schedule-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './doctors-available-schedule-add.component.html'
})
export class DoctorsAvailableScheduleAddComponent implements OnInit {

  doctorsAvailableScheduleService = inject(DoctorsAvailableScheduleService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  doctorValues?: Map<number,string>;

  addForm = new FormGroup({
    dayOfWeek: new FormControl(null, [Validators.maxLength(255)]),
    startDateTime: new FormControl(null),
    endDateTime: new FormControl(null),
    interval: new FormControl(null),
    active: new FormControl(false),
    doctor: new FormControl(null)
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@doctorsAvailableSchedule.create.success:Doctors Available Schedule was created successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.doctorsAvailableScheduleService.getDoctorValues()
        .subscribe({
          next: (data) => this.doctorValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new DoctorsAvailableScheduleDTO(this.addForm.value);
    this.doctorsAvailableScheduleService.createDoctorsAvailableSchedule(data)
        .subscribe({
          next: () => this.router.navigate(['/doctorsAvailableSchedules'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@doctorsAvailableSchedule.add.headline">Add Doctors Available Schedule</h1>
    <div>
        <a routerLink="/doctorsAvailableSchedules" class="btn btn-secondary" i18n="@@doctorsAvailableSchedule.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="dayOfWeek" i18n-label="@@doctorsAvailableSchedule.dayOfWeek.label" label="Day Of Week" />
    <app-input-row [group]="addForm" field="startDateTime" rowType="datetimepicker" i18n-label="@@doctorsAvailableSchedule.startDateTime.label" label="Start Date Time" />
    <app-input-row [group]="addForm" field="endDateTime" rowType="datetimepicker" i18n-label="@@doctorsAvailableSchedule.endDateTime.label" label="End Date Time" />
    <app-input-row [group]="addForm" field="interval" rowType="datetimepicker" i18n-label="@@doctorsAvailableSchedule.interval.label" label="Interval" />
    <app-input-row [group]="addForm" field="active" rowType="checkbox" i18n-label="@@doctorsAvailableSchedule.active.label" label="Active" />
    <app-input-row [group]="addForm" field="doctor" rowType="select" [options]="doctorValues" i18n-label="@@doctorsAvailableSchedule.doctor.label" label="Doctor" />
    <input type="submit" i18n-value="@@doctorsAvailableSchedule.add.headline" value="Add Doctors Available Schedule" class="btn btn-primary mt-4" />
</form>

// src/main/webapp/app/doctors-available-schedule/doctors-available-schedule-add.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { DoctorsAvailableScheduleDTO } from 'app/doctors-available-schedule/doctors-available-schedule-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    dayOfWeek: yup.string().emptyToNull().max(255),
    startDateTime: yup.string().emptyToNull(),
    endDateTime: yup.string().emptyToNull(),
    interval: yup.string().emptyToNull(),
    active: yup.bool(),
    doctor: yup.number().integer().emptyToNull()
  });
}

export default function DoctorsAvailableScheduleAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('doctorsAvailableSchedule.add.headline'));

  const navigate = useNavigate();
  const [doctorValues, setDoctorValues] = useState<Map<number,string>>(new Map());

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareRelations = async () => {
    try {
      const doctorValuesResponse = await axios.get('/api/doctorsAvailableSchedules/doctorValues');
      setDoctorValues(doctorValuesResponse.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareRelations();
  }, []);

  const createDoctorsAvailableSchedule = async (data: DoctorsAvailableScheduleDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/doctorsAvailableSchedules', data);
      navigate('/doctorsAvailableSchedules', {
            state: {
              msgSuccess: t('doctorsAvailableSchedule.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('doctorsAvailableSchedule.add.headline')}</h1>
      <div>
        <Link to="/doctorsAvailableSchedules" className="btn btn-secondary">{t('doctorsAvailableSchedule.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createDoctorsAvailableSchedule)} noValidate>
      <InputRow useFormResult={useFormResult} object="doctorsAvailableSchedule" field="dayOfWeek" />
      <InputRow useFormResult={useFormResult} object="doctorsAvailableSchedule" field="startDateTime" type="datetimepicker" />
      <InputRow useFormResult={useFormResult} object="doctorsAvailableSchedule" field="endDateTime" type="datetimepicker" />
      <InputRow useFormResult={useFormResult} object="doctorsAvailableSchedule" field="interval" type="datetimepicker" />
      <InputRow useFormResult={useFormResult} object="doctorsAvailableSchedule" field="active" type="checkbox" />
      <InputRow useFormResult={useFormResult} object="doctorsAvailableSchedule" field="doctor" type="select" options={doctorValues} />
      <input type="submit" value={t('doctorsAvailableSchedule.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}
