// src/main/webapp/app/doctors-available-schedule/doctors-available-schedule-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { DoctorsAvailableScheduleService } from 'app/doctors-available-schedule/doctors-available-schedule.service';
import { DoctorsAvailableScheduleDTO } from 'app/doctors-available-schedule/doctors-available-schedule.model';


@Component({
  selector: 'app-doctors-available-schedule-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './doctors-available-schedule-list.component.html'})
export class DoctorsAvailableScheduleListComponent implements OnInit, OnDestroy {

  doctorsAvailableScheduleService = inject(DoctorsAvailableScheduleService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  doctorsAvailableSchedules?: DoctorsAvailableScheduleDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@doctorsAvailableSchedule.delete.success:Doctors Available Schedule was removed successfully.`,
      'doctorsAvailableSchedule.schedule.doctorsAvailableSchedule.referenced': $localize`:@@doctorsAvailableSchedule.schedule.doctorsAvailableSchedule.referenced:This entity is still referenced by Schedule ${details?.id} via field Doctors Available Schedule.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.doctorsAvailableScheduleService.getAllDoctorsAvailableSchedules()
        .subscribe({
          next: (data) => this.doctorsAvailableSchedules = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.doctorsAvailableScheduleService.deleteDoctorsAvailableSchedule(id)
        .subscribe({
          next: () => this.router.navigate(['/doctorsAvailableSchedules'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => {
            if (error.error?.code === 'REFERENCED') {
              const messageParts = error.error.message.split(',');
              this.router.navigate(['/doctorsAvailableSchedules'], {
                state: {
                  msgError: this.getMessage(messageParts[0], { id: messageParts[1] })
                }
              });
              return;
            }
            this.errorHandler.handleServerError(error.error)
          }
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@doctorsAvailableSchedule.list.headline">Doctors Available Schedules</h1>
    <div>
        <a routerLink="/doctorsAvailableSchedules/add" class="btn btn-primary ms-2" i18n="@@doctorsAvailableSchedule.list.createNew">Create new Doctors Available Schedule</a>
    </div>
</div>
@if (!doctorsAvailableSchedules || doctorsAvailableSchedules.length === 0) {
<div i18n="@@doctorsAvailableSchedule.list.empty">No Doctors Available Schedules could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@doctorsAvailableSchedule.id.label">Id</th>
                <th scope="col" i18n="@@doctorsAvailableSchedule.dayOfWeek.label">Day Of Week</th>
                <th scope="col" i18n="@@doctorsAvailableSchedule.startDateTime.label">Start Date Time</th>
                <th scope="col" i18n="@@doctorsAvailableSchedule.endDateTime.label">End Date Time</th>
                <th scope="col" i18n="@@doctorsAvailableSchedule.interval.label">Interval</th>
                <th scope="col" i18n="@@doctorsAvailableSchedule.active.label">Active</th>
                <th scope="col" i18n="@@doctorsAvailableSchedule.doctor.label">Doctor</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (doctorsAvailableSchedule of doctorsAvailableSchedules; track doctorsAvailableSchedule.id) {
            <tr>
                <td>{{ doctorsAvailableSchedule.id }}</td>
                <td>{{ doctorsAvailableSchedule.dayOfWeek }}</td>
                <td>{{ doctorsAvailableSchedule.startDateTime }}</td>
                <td>{{ doctorsAvailableSchedule.endDateTime }}</td>
                <td>{{ doctorsAvailableSchedule.interval }}</td>
                <td>{{ doctorsAvailableSchedule.active }}</td>
                <td>{{ doctorsAvailableSchedule.doctor }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/doctorsAvailableSchedules/edit', doctorsAvailableSchedule.id]" class="btn btn-sm btn-secondary" i18n="@@doctorsAvailableSchedule.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(doctorsAvailableSchedule.id!)" class="btn btn-sm btn-secondary" i18n="@@doctorsAvailableSchedule.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}

// src/main/webapp/app/doctors-available-schedule/doctors-available-schedule-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { DoctorsAvailableScheduleDTO } from 'app/doctors-available-schedule/doctors-available-schedule-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function DoctorsAvailableScheduleList() {
  const { t } = useTranslation();
  useDocumentTitle(t('doctorsAvailableSchedule.list.headline'));

  const [doctorsAvailableSchedules, setDoctorsAvailableSchedules] = useState<DoctorsAvailableScheduleDTO[]>([]);
  const navigate = useNavigate();

  const getAllDoctorsAvailableSchedules = async () => {
    try {
      const response = await axios.get('/api/doctorsAvailableSchedules');
      setDoctorsAvailableSchedules(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/doctorsAvailableSchedules/' + id);
      navigate('/doctorsAvailableSchedules', {
            state: {
              msgInfo: t('doctorsAvailableSchedule.delete.success')
            }
          });
      getAllDoctorsAvailableSchedules();
    } catch (error: any) {
      if (error?.response?.data?.code === 'REFERENCED') {
        const messageParts = error.response.data.message.split(',');
        navigate('/doctorsAvailableSchedules', {
              state: {
                msgError: t(messageParts[0]!, { id: messageParts[1]! })
              }
            });
        return;
      }
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllDoctorsAvailableSchedules();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('doctorsAvailableSchedule.list.headline')}</h1>
      <div>
        <Link to="/doctorsAvailableSchedules/add" className="btn btn-primary ms-2">{t('doctorsAvailableSchedule.list.createNew')}</Link>
      </div>
    </div>
    {!doctorsAvailableSchedules || doctorsAvailableSchedules.length === 0 ? (
    <div>{t('doctorsAvailableSchedule.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('doctorsAvailableSchedule.id.label')}</th>
            <th scope="col">{t('doctorsAvailableSchedule.dayOfWeek.label')}</th>
            <th scope="col">{t('doctorsAvailableSchedule.startDateTime.label')}</th>
            <th scope="col">{t('doctorsAvailableSchedule.endDateTime.label')}</th>
            <th scope="col">{t('doctorsAvailableSchedule.interval.label')}</th>
            <th scope="col">{t('doctorsAvailableSchedule.active.label')}</th>
            <th scope="col">{t('doctorsAvailableSchedule.doctor.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {doctorsAvailableSchedules.map((doctorsAvailableSchedule) => (
          <tr key={doctorsAvailableSchedule.id}>
            <td>{doctorsAvailableSchedule.id}</td>
            <td>{doctorsAvailableSchedule.dayOfWeek}</td>
            <td>{doctorsAvailableSchedule.startDateTime}</td>
            <td>{doctorsAvailableSchedule.endDateTime}</td>
            <td>{doctorsAvailableSchedule.interval}</td>
            <td>{doctorsAvailableSchedule.active?.toString()}</td>
            <td>{doctorsAvailableSchedule.doctor}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/doctorsAvailableSchedules/edit/' + doctorsAvailableSchedule.id} className="btn btn-sm btn-secondary">{t('doctorsAvailableSchedule.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(doctorsAvailableSchedule.id!)} className="btn btn-sm btn-secondary">{t('doctorsAvailableSchedule.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}
