// src/main/webapp/app/doctors-available-schedule/doctors-available-schedule-edit.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate, useParams } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { DoctorsAvailableScheduleDTO } from 'app/doctors-available-schedule/doctors-available-schedule-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    dayOfWeek: yup.string().emptyToNull().max(255),
    startDateTime: yup.string().emptyToNull(),
    endDateTime: yup.string().emptyToNull(),
    interval: yup.string().emptyToNull(),
    active: yup.bool(),
    doctor: yup.number().integer().emptyToNull()
  });
}

export default function DoctorsAvailableScheduleEdit() {
  const { t } = useTranslation();
  useDocumentTitle(t('doctorsAvailableSchedule.edit.headline'));

  const navigate = useNavigate();
  const [doctorValues, setDoctorValues] = useState<Map<number,string>>(new Map());
  const params = useParams();
  const currentId = +params.id!;

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareForm = async () => {
    try {
      const doctorValuesResponse = await axios.get('/api/doctorsAvailableSchedules/doctorValues');
      setDoctorValues(doctorValuesResponse.data);
      const data = (await axios.get('/api/doctorsAvailableSchedules/' + currentId)).data;
      useFormResult.reset(data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareForm();
  }, []);

  const updateDoctorsAvailableSchedule = async (data: DoctorsAvailableScheduleDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.put('/api/doctorsAvailableSchedules/' + currentId, data);
      navigate('/doctorsAvailableSchedules', {
            state: {
              msgSuccess: t('doctorsAvailableSchedule.update.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('doctorsAvailableSchedule.edit.headline')}</h1>
      <div>
        <Link to="/doctorsAvailableSchedules" className="btn btn-secondary">{t('doctorsAvailableSchedule.edit.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(updateDoctorsAvailableSchedule)} noValidate>
      <InputRow useFormResult={useFormResult} object="doctorsAvailableSchedule" field="id" disabled={true} type="number" />
      <InputRow useFormResult={useFormResult} object="doctorsAvailableSchedule" field="dayOfWeek" />
      <InputRow useFormResult={useFormResult} object="doctorsAvailableSchedule" field="startDateTime" type="datetimepicker" />
      <InputRow useFormResult={useFormResult} object="doctorsAvailableSchedule" field="endDateTime" type="datetimepicker" />
      <InputRow useFormResult={useFormResult} object="doctorsAvailableSchedule" field="interval" type="datetimepicker" />
      <InputRow useFormResult={useFormResult} object="doctorsAvailableSchedule" field="active" type="checkbox" />
      <InputRow useFormResult={useFormResult} object="doctorsAvailableSchedule" field="doctor" type="select" options={doctorValues} />
      <input type="submit" value={t('doctorsAvailableSchedule.edit.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/doctors-available-schedule/doctors-available-schedule-edit.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { DoctorsAvailableScheduleService } from 'app/doctors-available-schedule/doctors-available-schedule.service';
import { DoctorsAvailableScheduleDTO } from 'app/doctors-available-schedule/doctors-available-schedule.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { updateForm } from 'app/common/utils';


@Component({
  selector: 'app-doctors-available-schedule-edit',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './doctors-available-schedule-edit.component.html'
})
export class DoctorsAvailableScheduleEditComponent implements OnInit {

  doctorsAvailableScheduleService = inject(DoctorsAvailableScheduleService);
  route = inject(ActivatedRoute);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  doctorValues?: Map<number,string>;
  currentId?: number;

  editForm = new FormGroup({
    id: new FormControl({ value: null, disabled: true }),
    dayOfWeek: new FormControl(null, [Validators.maxLength(255)]),
    startDateTime: new FormControl(null),
    endDateTime: new FormControl(null),
    interval: new FormControl(null),
    active: new FormControl(false),
    doctor: new FormControl(null)
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      updated: $localize`:@@doctorsAvailableSchedule.update.success:Doctors Available Schedule was updated successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.currentId = +this.route.snapshot.params['id'];
    this.doctorsAvailableScheduleService.getDoctorValues()
        .subscribe({
          next: (data) => this.doctorValues = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
    this.doctorsAvailableScheduleService.getDoctorsAvailableSchedule(this.currentId!)
        .subscribe({
          next: (data) => updateForm(this.editForm, data),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.editForm.markAllAsTouched();
    if (!this.editForm.valid) {
      return;
    }
    const data = new DoctorsAvailableScheduleDTO(this.editForm.value);
    this.doctorsAvailableScheduleService.updateDoctorsAvailableSchedule(this.currentId!, data)
        .subscribe({
          next: () => this.router.navigate(['/doctorsAvailableSchedules'], {
            state: {
              msgSuccess: this.getMessage('updated')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.editForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@doctorsAvailableSchedule.edit.headline">Edit Doctors Available Schedule</h1>
    <div>
        <a routerLink="/doctorsAvailableSchedules" class="btn btn-secondary" i18n="@@doctorsAvailableSchedule.edit.back">Back to list</a>
    </div>
</div>
<form [formGroup]="editForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="editForm" field="id" rowType="number" i18n-label="@@doctorsAvailableSchedule.id.label" label="Id" />
    <app-input-row [group]="editForm" field="dayOfWeek" i18n-label="@@doctorsAvailableSchedule.dayOfWeek.label" label="Day Of Week" />
    <app-input-row [group]="editForm" field="startDateTime" rowType="datetimepicker" i18n-label="@@doctorsAvailableSchedule.startDateTime.label" label="Start Date Time" />
    <app-input-row [group]="editForm" field="endDateTime" rowType="datetimepicker" i18n-label="@@doctorsAvailableSchedule.endDateTime.label" label="End Date Time" />
    <app-input-row [group]="editForm" field="interval" rowType="datetimepicker" i18n-label="@@doctorsAvailableSchedule.interval.label" label="Interval" />
    <app-input-row [group]="editForm" field="active" rowType="checkbox" i18n-label="@@doctorsAvailableSchedule.active.label" label="Active" />
    <app-input-row [group]="editForm" field="doctor" rowType="select" [options]="doctorValues" i18n-label="@@doctorsAvailableSchedule.doctor.label" label="Doctor" />
    <input type="submit" i18n-value="@@doctorsAvailableSchedule.edit.headline" value="Edit Doctors Available Schedule" class="btn btn-primary mt-4" />
</form>
