// src/main/webapp/app/document/document-add.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { DocumentDTO } from 'app/document/document-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    documentType: yup.string().emptyToNull(),
    file: yup.object().emptyToNull().json().required(),
    filename: yup.string().emptyToNull().max(255),
    fileType: yup.string().emptyToNull().max(255)
  });
}

export default function DocumentAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('document.add.headline'));

  const navigate = useNavigate();

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const createDocument = async (data: DocumentDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/documents', data);
      navigate('/documents', {
            state: {
              msgSuccess: t('document.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('document.add.headline')}</h1>
      <div>
        <Link to="/documents" className="btn btn-secondary">{t('document.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createDocument)} noValidate>
      <InputRow useFormResult={useFormResult} object="document" field="documentType" required={true} type="select" options={{'CPF': 'CPF', 'RG': 'RG', 'ATESTADO': 'ATESTADO', 'PLANOSAUDE': 'PLANOSAUDE', 'NEWSLETTER': 'NEWSLETTER', 'OTHERS': 'OTHERS'}} />
      <InputRow useFormResult={useFormResult} object="document" field="file" required={true} type="file" />
      <InputRow useFormResult={useFormResult} object="document" field="filename" />
      <InputRow useFormResult={useFormResult} object="document" field="fileType" />
      <input type="submit" value={t('document.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/document/document-add.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { DocumentService } from 'app/document/document.service';
import { DocumentDTO } from 'app/document/document.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';


@Component({
  selector: 'app-document-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './document-add.component.html'
})
export class DocumentAddComponent {

  documentService = inject(DocumentService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  addForm = new FormGroup({
    documentType: new FormControl(null, [Validators.required]),
    file: new FormControl(null, [Validators.required]),
    filename: new FormControl(null, [Validators.maxLength(255)]),
    fileType: new FormControl(null, [Validators.maxLength(255)])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@document.create.success:Document was created successfully.`
    };
    return messages[key];
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new DocumentDTO(this.addForm.value);
    this.documentService.createDocument(data)
        .subscribe({
          next: () => this.router.navigate(['/documents'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@document.add.headline">Add Document</h1>
    <div>
        <a routerLink="/documents" class="btn btn-secondary" i18n="@@document.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="documentType" rowType="select" [options]="{'CPF': 'CPF', 'RG': 'RG', 'ATESTADO': 'ATESTADO', 'PLANOSAUDE': 'PLANOSAUDE', 'NEWSLETTER': 'NEWSLETTER', 'OTHERS': 'OTHERS'}" i18n-label="@@document.documentType.label" label="Document Type" />
    <app-input-row [group]="addForm" field="file" rowType="file" i18n-label="@@document.file.label" label="File" />
    <app-input-row [group]="addForm" field="filename" i18n-label="@@document.filename.label" label="Filename" />
    <app-input-row [group]="addForm" field="fileType" i18n-label="@@document.fileType.label" label="File Type" />
    <input type="submit" i18n-value="@@document.add.headline" value="Add Document" class="btn btn-primary mt-4" />
</form>
