// src/main/webapp/app/document/document-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { DocumentService } from 'app/document/document.service';
import { DocumentDTO } from 'app/document/document.model';


@Component({
  selector: 'app-document-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './document-list.component.html'})
export class DocumentListComponent implements OnInit, OnDestroy {

  documentService = inject(DocumentService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  documents?: DocumentDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@document.delete.success:Document was removed successfully.`    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.documentService.getAllDocuments()
        .subscribe({
          next: (data) => this.documents = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.documentService.deleteDocument(id)
        .subscribe({
          next: () => this.router.navigate(['/documents'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@document.list.headline">Documents</h1>
    <div>
        <a routerLink="/documents/add" class="btn btn-primary ms-2" i18n="@@document.list.createNew">Create new Document</a>
    </div>
</div>
@if (!documents || documents.length === 0) {
<div i18n="@@document.list.empty">No Documents could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@document.id.label">Id</th>
                <th scope="col" i18n="@@document.documentType.label">Document Type</th>
                <th scope="col" i18n="@@document.filename.label">Filename</th>
                <th scope="col" i18n="@@document.fileType.label">File Type</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (document of documents; track document.id) {
            <tr>
                <td>{{ document.id }}</td>
                <td>{{ document.documentType }}</td>
                <td>{{ document.filename }}</td>
                <td>{{ document.fileType }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/documents/edit', document.id]" class="btn btn-sm btn-secondary" i18n="@@document.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(document.id!)" class="btn btn-sm btn-secondary" i18n="@@document.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}

// src/main/webapp/app/document/document-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { DocumentDTO } from 'app/document/document-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function DocumentList() {
  const { t } = useTranslation();
  useDocumentTitle(t('document.list.headline'));

  const [documents, setDocuments] = useState<DocumentDTO[]>([]);
  const navigate = useNavigate();

  const getAllDocuments = async () => {
    try {
      const response = await axios.get('/api/documents');
      setDocuments(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/documents/' + id);
      navigate('/documents', {
            state: {
              msgInfo: t('document.delete.success')
            }
          });
      getAllDocuments();
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllDocuments();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('document.list.headline')}</h1>
      <div>
        <Link to="/documents/add" className="btn btn-primary ms-2">{t('document.list.createNew')}</Link>
      </div>
    </div>
    {!documents || documents.length === 0 ? (
    <div>{t('document.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('document.id.label')}</th>
            <th scope="col">{t('document.documentType.label')}</th>
            <th scope="col">{t('document.filename.label')}</th>
            <th scope="col">{t('document.fileType.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {documents.map((document) => (
          <tr key={document.id}>
            <td>{document.id}</td>
            <td>{document.documentType}</td>
            <td>{document.filename}</td>
            <td>{document.fileType}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/documents/edit/' + document.id} className="btn btn-sm btn-secondary">{t('document.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(document.id!)} className="btn btn-sm btn-secondary">{t('document.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}
