// src/main/webapp/app/document/document-edit.tsx
import React, { useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate, useParams } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { DocumentDTO } from 'app/document/document-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    documentType: yup.string().emptyToNull(),
    file: yup.object().emptyToNull().json().required(),
    filename: yup.string().emptyToNull().max(255),
    fileType: yup.string().emptyToNull().max(255)
  });
}

export default function DocumentEdit() {
  const { t } = useTranslation();
  useDocumentTitle(t('document.edit.headline'));

  const navigate = useNavigate();
  const params = useParams();
  const currentId = +params.id!;

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareForm = async () => {
    try {
      const data = (await axios.get('/api/documents/' + currentId)).data;
      if (data.file) {
        data.file = JSON.stringify(data.file, undefined, 2);
      }
      useFormResult.reset(data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareForm();
  }, []);

  const updateDocument = async (data: DocumentDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.put('/api/documents/' + currentId, data);
      navigate('/documents', {
            state: {
              msgSuccess: t('document.update.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('document.edit.headline')}</h1>
      <div>
        <Link to="/documents" className="btn btn-secondary">{t('document.edit.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(updateDocument)} noValidate>
      <InputRow useFormResult={useFormResult} object="document" field="id" disabled={true} type="number" />
      <InputRow useFormResult={useFormResult} object="document" field="documentType" required={true} type="select" options={{'CPF': 'CPF', 'RG': 'RG', 'ATESTADO': 'ATESTADO', 'PLANOSAUDE': 'PLANOSAUDE', 'NEWSLETTER': 'NEWSLETTER', 'OTHERS': 'OTHERS'}} />
      <InputRow useFormResult={useFormResult} object="document" field="file" required={true} type="file" downloadLink={'/api/phoness/' + currentId + '/file'} />
      <InputRow useFormResult={useFormResult} object="document" field="filename" />
      <InputRow useFormResult={useFormResult} object="document" field="fileType" />
      <input type="submit" value={t('document.edit.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}

// src/main/webapp/app/document/document-edit.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { DocumentService } from 'app/document/document.service';
import { DocumentDTO } from 'app/document/document.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { updateForm } from 'app/common/utils';


@Component({
  selector: 'app-document-edit',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './document-edit.component.html'
})
export class DocumentEditComponent implements OnInit {

  documentService = inject(DocumentService);
  route = inject(ActivatedRoute);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  currentId?: number;

  editForm = new FormGroup({
    id: new FormControl({ value: null, disabled: true }),
    documentType: new FormControl(null, [Validators.required]),
    file: new FormControl(null, [Validators.required]),
    filename: new FormControl(null, [Validators.maxLength(255)]),
    fileType: new FormControl(null, [Validators.maxLength(255)])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      updated: $localize`:@@document.update.success:Document was updated successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.currentId = +this.route.snapshot.params['id'];
    this.documentService.getDocument(this.currentId!)
        .subscribe({
          next: (data) => updateForm(this.editForm, data),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.editForm.markAllAsTouched();
    if (!this.editForm.valid) {
      return;
    }
    const data = new DocumentDTO(this.editForm.value);
    this.documentService.updateDocument(this.currentId!, data)
        .subscribe({
          next: () => this.router.navigate(['/documents'], {
            state: {
              msgSuccess: this.getMessage('updated')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.editForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@document.edit.headline">Edit Document</h1>
    <div>
        <a routerLink="/documents" class="btn btn-secondary" i18n="@@document.edit.back">Back to list</a>
    </div>
</div>
<form [formGroup]="editForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="editForm" field="id" rowType="number" i18n-label="@@document.id.label" label="Id" />
    <app-input-row [group]="editForm" field="documentType" rowType="select" [options]="{'CPF': 'CPF', 'RG': 'RG', 'ATESTADO': 'ATESTADO', 'PLANOSAUDE': 'PLANOSAUDE', 'NEWSLETTER': 'NEWSLETTER', 'OTHERS': 'OTHERS'}" i18n-label="@@document.documentType.label" label="Document Type" />
    <app-input-row [group]="editForm" field="file" rowType="file" [downloadLink]="'/api/phoness/' + currentId + '/file'" i18n-label="@@document.file.label" label="File" />
    <app-input-row [group]="editForm" field="filename" i18n-label="@@document.filename.label" label="Filename" />
    <app-input-row [group]="editForm" field="fileType" i18n-label="@@document.fileType.label" label="File Type" />
    <input type="submit" i18n-value="@@document.edit.headline" value="Edit Document" class="btn btn-primary mt-4" />
</form>
