// src/main/webapp/app/specialty/specialty-add.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { SpecialtyService } from 'app/specialty/specialty.service';
import { SpecialtyDTO } from 'app/specialty/specialty.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';


@Component({
  selector: 'app-specialty-add',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './specialty-add.component.html'
})
export class SpecialtyAddComponent {

  specialtyService = inject(SpecialtyService);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  addForm = new FormGroup({
    name: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    description: new FormControl(null, [Validators.maxLength(255)])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      created: $localize`:@@specialty.create.success:Specialty was created successfully.`
    };
    return messages[key];
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.addForm.markAllAsTouched();
    if (!this.addForm.valid) {
      return;
    }
    const data = new SpecialtyDTO(this.addForm.value);
    this.specialtyService.createSpecialty(data)
        .subscribe({
          next: () => this.router.navigate(['/specialties'], {
            state: {
              msgSuccess: this.getMessage('created')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.addForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@specialty.add.headline">Add Specialty</h1>
    <div>
        <a routerLink="/specialties" class="btn btn-secondary" i18n="@@specialty.add.back">Back to list</a>
    </div>
</div>
<form [formGroup]="addForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="addForm" field="name" i18n-label="@@specialty.name.label" label="Name" />
    <app-input-row [group]="addForm" field="description" i18n-label="@@specialty.description.label" label="Description" />
    <input type="submit" i18n-value="@@specialty.add.headline" value="Add Specialty" class="btn btn-primary mt-4" />
</form>

// src/main/webapp/app/specialty/specialty-add.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { SpecialtyDTO } from 'app/specialty/specialty-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    name: yup.string().emptyToNull().max(255).required(),
    description: yup.string().emptyToNull().max(255)
  });
}

export default function SpecialtyAdd() {
  const { t } = useTranslation();
  useDocumentTitle(t('specialty.add.headline'));

  const navigate = useNavigate();

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const createSpecialty = async (data: SpecialtyDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.post('/api/specialties', data);
      navigate('/specialties', {
            state: {
              msgSuccess: t('specialty.create.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('specialty.add.headline')}</h1>
      <div>
        <Link to="/specialties" className="btn btn-secondary">{t('specialty.add.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(createSpecialty)} noValidate>
      <InputRow useFormResult={useFormResult} object="specialty" field="name" required={true} />
      <InputRow useFormResult={useFormResult} object="specialty" field="description" />
      <input type="submit" value={t('specialty.add.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}
