// src/main/webapp/app/specialty/specialty-edit.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { InputRowComponent } from 'app/common/input-row/input-row.component';
import { SpecialtyService } from 'app/specialty/specialty.service';
import { SpecialtyDTO } from 'app/specialty/specialty.model';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { updateForm } from 'app/common/utils';


@Component({
  selector: 'app-specialty-edit',
  imports: [CommonModule, RouterLink, ReactiveFormsModule, InputRowComponent],
  templateUrl: './specialty-edit.component.html'
})
export class SpecialtyEditComponent implements OnInit {

  specialtyService = inject(SpecialtyService);
  route = inject(ActivatedRoute);
  router = inject(Router);
  errorHandler = inject(ErrorHandler);

  currentId?: number;

  editForm = new FormGroup({
    id: new FormControl({ value: null, disabled: true }),
    name: new FormControl(null, [Validators.required, Validators.maxLength(255)]),
    description: new FormControl(null, [Validators.maxLength(255)])
  }, { updateOn: 'submit' });

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      updated: $localize`:@@specialty.update.success:Specialty was updated successfully.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.currentId = +this.route.snapshot.params['id'];
    this.specialtyService.getSpecialty(this.currentId!)
        .subscribe({
          next: (data) => updateForm(this.editForm, data),
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  handleSubmit() {
    window.scrollTo(0, 0);
    this.editForm.markAllAsTouched();
    if (!this.editForm.valid) {
      return;
    }
    const data = new SpecialtyDTO(this.editForm.value);
    this.specialtyService.updateSpecialty(this.currentId!, data)
        .subscribe({
          next: () => this.router.navigate(['/specialties'], {
            state: {
              msgSuccess: this.getMessage('updated')
            }
          }),
          error: (error) => this.errorHandler.handleServerError(error.error, this.editForm, this.getMessage)
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@specialty.edit.headline">Edit Specialty</h1>
    <div>
        <a routerLink="/specialties" class="btn btn-secondary" i18n="@@specialty.edit.back">Back to list</a>
    </div>
</div>
<form [formGroup]="editForm" (ngSubmit)="handleSubmit()">
    <app-input-row [group]="editForm" field="id" rowType="number" i18n-label="@@specialty.id.label" label="Id" />
    <app-input-row [group]="editForm" field="name" i18n-label="@@specialty.name.label" label="Name" />
    <app-input-row [group]="editForm" field="description" i18n-label="@@specialty.description.label" label="Description" />
    <input type="submit" i18n-value="@@specialty.edit.headline" value="Edit Specialty" class="btn btn-primary mt-4" />
</form>

// src/main/webapp/app/specialty/specialty-edit.tsx
import React, { useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate, useParams } from 'react-router';
import { handleServerError, setYupDefaults } from 'app/common/utils';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { SpecialtyDTO } from 'app/specialty/specialty-model';
import axios from 'axios';
import InputRow from 'app/common/input-row/input-row';
import useDocumentTitle from 'app/common/use-document-title';
import * as yup from 'yup';


function getSchema() {
  setYupDefaults();
  return yup.object({
    name: yup.string().emptyToNull().max(255).required(),
    description: yup.string().emptyToNull().max(255)
  });
}

export default function SpecialtyEdit() {
  const { t } = useTranslation();
  useDocumentTitle(t('specialty.edit.headline'));

  const navigate = useNavigate();
  const params = useParams();
  const currentId = +params.id!;

  const useFormResult = useForm({
    resolver: yupResolver(getSchema()),
  });

  const prepareForm = async () => {
    try {
      const data = (await axios.get('/api/specialties/' + currentId)).data;
      useFormResult.reset(data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    prepareForm();
  }, []);

  const updateSpecialty = async (data: SpecialtyDTO) => {
    window.scrollTo(0, 0);
    try {
      await axios.put('/api/specialties/' + currentId, data);
      navigate('/specialties', {
            state: {
              msgSuccess: t('specialty.update.success')
            }
          });
    } catch (error: any) {
      handleServerError(error, navigate, useFormResult.setError, t);
    }
  };

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('specialty.edit.headline')}</h1>
      <div>
        <Link to="/specialties" className="btn btn-secondary">{t('specialty.edit.back')}</Link>
      </div>
    </div>
    <form onSubmit={useFormResult.handleSubmit(updateSpecialty)} noValidate>
      <InputRow useFormResult={useFormResult} object="specialty" field="id" disabled={true} type="number" />
      <InputRow useFormResult={useFormResult} object="specialty" field="name" required={true} />
      <InputRow useFormResult={useFormResult} object="specialty" field="description" />
      <input type="submit" value={t('specialty.edit.headline')} className="btn btn-primary mt-4" />
    </form>
  </>);
}
