// src/main/webapp/app/specialty/specialty-list.tsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link, useNavigate } from 'react-router';
import { handleServerError } from 'app/common/utils';
import { SpecialtyDTO } from 'app/specialty/specialty-model';
import axios from 'axios';
import useDocumentTitle from 'app/common/use-document-title';


export default function SpecialtyList() {
  const { t } = useTranslation();
  useDocumentTitle(t('specialty.list.headline'));

  const [specialties, setSpecialties] = useState<SpecialtyDTO[]>([]);
  const navigate = useNavigate();

  const getAllSpecialties = async () => {
    try {
      const response = await axios.get('/api/specialties');
      setSpecialties(response.data);
    } catch (error: any) {
      handleServerError(error, navigate);
    }
  };

  const confirmDelete = async (id: number) => {
    if (!confirm(t('delete.confirm'))) {
      return;
    }
    try {
      await axios.delete('/api/specialties/' + id);
      navigate('/specialties', {
            state: {
              msgInfo: t('specialty.delete.success')
            }
          });
      getAllSpecialties();
    } catch (error: any) {
      if (error?.response?.data?.code === 'REFERENCED') {
        const messageParts = error.response.data.message.split(',');
        navigate('/specialties', {
              state: {
                msgError: t(messageParts[0]!, { id: messageParts[1]! })
              }
            });
        return;
      }
      handleServerError(error, navigate);
    }
  };

  useEffect(() => {
    getAllSpecialties();
  }, []);

  return (<>
    <div className="d-flex flex-wrap mb-4">
      <h1 className="flex-grow-1">{t('specialty.list.headline')}</h1>
      <div>
        <Link to="/specialties/add" className="btn btn-primary ms-2">{t('specialty.list.createNew')}</Link>
      </div>
    </div>
    {!specialties || specialties.length === 0 ? (
    <div>{t('specialty.list.empty')}</div>
    ) : (
    <div className="table-responsive">
      <table className="table table-striped table-hover align-middle">
        <thead>
          <tr>
            <th scope="col">{t('specialty.id.label')}</th>
            <th scope="col">{t('specialty.name.label')}</th>
            <th scope="col">{t('specialty.description.label')}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {specialties.map((specialty) => (
          <tr key={specialty.id}>
            <td>{specialty.id}</td>
            <td>{specialty.name}</td>
            <td>{specialty.description}</td>
            <td>
              <div className="float-end text-nowrap">
                <Link to={'/specialties/edit/' + specialty.id} className="btn btn-sm btn-secondary">{t('specialty.list.edit')}</Link>
                <span> </span>
                <button type="button" onClick={() => confirmDelete(specialty.id!)} className="btn btn-sm btn-secondary">{t('specialty.list.delete')}</button>
              </div>
            </td>
          </tr>
          ))}
        </tbody>
      </table>
    </div>
    )}
  </>);
}

// src/main/webapp/app/specialty/specialty-list.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ErrorHandler } from 'app/common/error-handler.injectable';
import { SpecialtyService } from 'app/specialty/specialty.service';
import { SpecialtyDTO } from 'app/specialty/specialty.model';


@Component({
  selector: 'app-specialty-list',
  imports: [CommonModule, RouterLink],
  templateUrl: './specialty-list.component.html'})
export class SpecialtyListComponent implements OnInit, OnDestroy {

  specialtyService = inject(SpecialtyService);
  errorHandler = inject(ErrorHandler);
  router = inject(Router);
  specialties?: SpecialtyDTO[];
  navigationSubscription?: Subscription;

  getMessage(key: string, details?: any) {
    const messages: Record<string, string> = {
      confirm: $localize`:@@delete.confirm:Do you really want to delete this element? This cannot be undone.`,
      deleted: $localize`:@@specialty.delete.success:Specialty was removed successfully.`,
      'specialty.doctor.specialty.referenced': $localize`:@@specialty.doctor.specialty.referenced:This entity is still referenced by Doctor ${details?.id} via field Specialty.`
    };
    return messages[key];
  }

  ngOnInit() {
    this.loadData();
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.loadData();
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription!.unsubscribe();
  }
  
  loadData() {
    this.specialtyService.getAllSpecialties()
        .subscribe({
          next: (data) => this.specialties = data,
          error: (error) => this.errorHandler.handleServerError(error.error)
        });
  }

  confirmDelete(id: number) {
    if (!confirm(this.getMessage('confirm'))) {
      return;
    }
    this.specialtyService.deleteSpecialty(id)
        .subscribe({
          next: () => this.router.navigate(['/specialties'], {
            state: {
              msgInfo: this.getMessage('deleted')
            }
          }),
          error: (error) => {
            if (error.error?.code === 'REFERENCED') {
              const messageParts = error.error.message.split(',');
              this.router.navigate(['/specialties'], {
                state: {
                  msgError: this.getMessage(messageParts[0], { id: messageParts[1] })
                }
              });
              return;
            }
            this.errorHandler.handleServerError(error.error)
          }
        });
  }

}

<div class="d-flex flex-wrap mb-4">
    <h1 class="flex-grow-1" i18n="@@specialty.list.headline">Specialties</h1>
    <div>
        <a routerLink="/specialties/add" class="btn btn-primary ms-2" i18n="@@specialty.list.createNew">Create new Specialty</a>
    </div>
</div>
@if (!specialties || specialties.length === 0) {
<div i18n="@@specialty.list.empty">No Specialties could be found.</div>
} @else {
<div class="table-responsive">
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
                <th scope="col" i18n="@@specialty.id.label">Id</th>
                <th scope="col" i18n="@@specialty.name.label">Name</th>
                <th scope="col" i18n="@@specialty.description.label">Description</th>
                <th><!-- --></th>
            </tr>
        </thead>
        <tbody>
            @for (specialty of specialties; track specialty.id) {
            <tr>
                <td>{{ specialty.id }}</td>
                <td>{{ specialty.name }}</td>
                <td>{{ specialty.description }}</td>
                <td>
                    <div class="float-end text-nowrap">
                        <a [routerLink]="['/specialties/edit', specialty.id]" class="btn btn-sm btn-secondary" i18n="@@specialty.list.edit">Edit</a>
                        <button type="button" (click)="confirmDelete(specialty.id!)" class="btn btn-sm btn-secondary" i18n="@@specialty.list.delete">Delete</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
}
